## 1. ADD NEEDED LIBRARY

In [59]:
import pandas as pd
pd.set_option('display.max_info_columns', 1000)
pd.set_option('display.max_info_rows', 1000)

## 2. READ FILES

In [60]:
# formulation dataset has 3 differents including 'UV Formulations', 'Core Formulations', and 'Outer Formulations'
uv          = pd.read_excel('../data/raw/formulation_database.xlsx', sheet_name = 'UV Formulations')
core        = pd.read_excel('../data/raw/formulation_database.xlsx', sheet_name = 'Core Formulations ')
outer       = pd.read_csv('../data/raw/outer_formulation.csv')

# starting materials dataset also has 3 different types of batch, corresponding to 3 formulas.
core_batch  = pd.read_excel('../data/raw/starting_materials.xlsx', sheet_name='Core QC_1')
uv_batch    = pd.read_excel('../data/raw/starting_materials.xlsx', sheet_name='UV QC_1')
outer_batch = pd.read_excel('../data/raw/starting_materials.xlsx', sheet_name='Outer QC')

# axf dataset is the primary production data, including the combination of main materials (UV, core, outer) along with other materials and surrounding conditions.
mix         = pd.read_excel('../data/raw/axf_manufacturing_run.xlsx')

# durability dataset show the quality check result of each axf combination.
result      = pd.read_excel('../data/raw/durability_results.xlsx')

c:\Users\ASUS\anaconda3\Lib\site-packages\openpyxl\worksheet\_read_only.py:85: UserWarning: Data Validation extension is not supported and will be removed
  for idx, row in parser.parse():

## 3. UV FORMULATIONS CLEANNING

In [61]:
print(uv.columns)
print('-'*50)
uv.head(20)

Index(['Tom', 'Unnamed: 1',
       'Welcome to the big formulation database! This page is for UV and next is for core.',
       'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7',
       'Unnamed: 8', 'Unnamed: 9',
       ...
       'Unnamed: 317', 'Unnamed: 318', 'Unnamed: 319', 'Unnamed: 320',
       'Unnamed: 321', 'Unnamed: 322', 'Unnamed: 323', 'Unnamed: 324',
       'Unnamed: 325', 'Unnamed: 326'],
      dtype='object', length=327)
--------------------------------------------------

,Tom,Unnamed: 1,Welcome to the big formulation database! This page is for UV and next is for core.,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 317,Unnamed: 318,Unnamed: 319,Unnamed: 320,Unnamed: 321,Unnamed: 322,Unnamed: 323,Unnamed: 324,Unnamed: 325,Unnamed: 326
0,Kayleigh,NaN,"To find formulations you want, try the filter ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Sian,NaN,Raw material amounts are in Wt%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Luke,NaN,Any problems come and find me:) Special thanks...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Izzy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,FILTERING,NaN,ESBOA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,Sample,50:50 ESBOA:PEG,THB03-03,THB03-32,AUF010,AUF015,AUF042,...,AUF377,AUF378,AUF379,AUF380,AUF381,AUF382,AUF383,AUF384,AUF385,AUF386
7,NaN,NaN,NaN,Operator,Tom,Tom,Tom,Kayleigh,Kayleigh,Kayleigh,...,Kayleigh,Izzy,Izzy,Kayleigh,Izzy,Izzy,Izzy,Izzy,Izzy,Izzy
8,NaN,NaN,NaN,Made?,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,yes,NaN,NaN,yes,yes,yes,NaN,NaN,NaN
9,NaN,NaN,NaN,Date,2023-10-26 00:00:00,2023-10-26 00:00:00,2023-11-03 00:00:00,2022-08-30 00:00:00,2022-11-01 00:00:00,2023-02-08 00:00:00,...,2025-12-10 00:00:00,2025-12-18 00:00:00,2025-12-18 00:00:00,2024-01-06 00:00:00,2026-01-12 00:00:00,2026-01-21 00:00:00,2026-01-21 00:00:00,2026-01-21 00:00:00,2026-01-21 00:00:00,2026-01-21 00:00:00
10,MW,Func,NaN,Location of Data,THB Project 2,THB Project 2,THB Project 2,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,1200,3,Oligomers,ESBOA,47.5,66.5,NaN,NaN,NaN,20,...,NaN,NaN,NaN,NaN,NaN,47.5,47.5,NaN,NaN,NaN
12,NaN,NaN,NaN,Epoxy:GPTA 75:25,NaN,NaN,NaN,55.3,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,11000,2,NaN,Miramer PU2560,NaN,NaN,NaN,NaN,49,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,3140,2,NaN,Photocryl DP408NT (40% DPGDA),NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,23.75,23.75,NaN,36,NaN,NaN,23.75,NaN,47.5
15,3560,6,NaN,Miramer U360NT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,3030,2,NaN,Miramer U3195NT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,Miramer U3926NT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,Miramer U3969NT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,3500,9,NaN,Miramer MU9800,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

The first 5 rows and the first 3 columns are actually unimportant as they contain information unnecessary for analysis and will therefore be removed. <br>
<br>
If we observe starting from column 4 (temporarily named 'Unnamed: 3'), which contains the names of formula attributes, then the removal of unnecessary rows will be based on this column. <br>
<br>
Similarly, line 6 contains important information about the names of the experimental samples.

In [62]:
# drop unecessary rows
uv = uv.dropna(subset=['Unnamed: 3'])

# drop unecessary columns
row_index = 6
uv = uv.dropna(axis=1, subset=[row_index])

uv.head(5)

,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,...,Unnamed: 317,Unnamed: 318,Unnamed: 319,Unnamed: 320,Unnamed: 321,Unnamed: 322,Unnamed: 323,Unnamed: 324,Unnamed: 325,Unnamed: 326
6,Sample,50:50 ESBOA:PEG,THB03-03,THB03-32,AUF010,AUF015,AUF042,AUF069,AUF070,AUF071,...,AUF377,AUF378,AUF379,AUF380,AUF381,AUF382,AUF383,AUF384,AUF385,AUF386
7,Operator,Tom,Tom,Tom,Kayleigh,Kayleigh,Kayleigh,Kayleigh,Kayleigh,Kayleigh,...,Kayleigh,Izzy,Izzy,Kayleigh,Izzy,Izzy,Izzy,Izzy,Izzy,Izzy
8,Made?,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,yes,NaN,NaN,yes,yes,yes,NaN,NaN,NaN
9,Date,2023-10-26 00:00:00,2023-10-26 00:00:00,2023-11-03 00:00:00,2022-08-30 00:00:00,2022-11-01 00:00:00,2023-02-08 00:00:00,2023-12-04 00:00:00,2023-12-04 00:00:00,2023-12-06 00:00:00,...,2025-12-10 00:00:00,2025-12-18 00:00:00,2025-12-18 00:00:00,2024-01-06 00:00:00,2026-01-12 00:00:00,2026-01-21 00:00:00,2026-01-21 00:00:00,2026-01-21 00:00:00,2026-01-21 00:00:00,2026-01-21 00:00:00
10,Location of Data,THB Project 2,THB Project 2,THB Project 2,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Now we're going to rotate it and reset the index.

In [63]:
# create a copy of 'uv' and assign it to 'df' so as not to directly modify the original 'uv'.
df = uv.copy()

# get all the first rows and columns as the new label.
row_labels = df.iloc[:, 0]

# the data will be extracted from all rows starting from the second column.
data = df.iloc[:, 1:].copy()

# set the first column as the index for all rows.
data.index = row_labels

# discard items with missing labels.
data = data.loc[data.index.notna()]

# rotate the data frame
uv = data.T.reset_index(drop=True)

# delete column names and delete index names.
uv.columns.name = None
uv.index.name = None

uv.head(5)

,Sample,Operator,Made?,Date,Location of Data,ESBOA,Epoxy:GPTA 75:25,Miramer PU2560,Photocryl DP408NT (40% DPGDA),Miramer U360NT,...,GC1000Z,Total,Viscosity @30 °C,Acrylate density,Flexibility,Cure,"WVP (1= good, 2= mid, 3= poor)",WVP numbers (g/(m2/24hr)) -Pulse data,WVP number - in house data,WVP in-house repeat of pulse films
0,50:50 ESBOA:PEG,Tom,NaN,2023-10-26 00:00:00,THB Project 2,47.5,NaN,NaN,NaN,NaN,...,NaN,100,NaN,3.841131,NaN,NaN,NaN,NaN,NaN,NaN
1,THB03-03,Tom,NaN,2023-10-26 00:00:00,THB Project 2,66.5,NaN,NaN,NaN,NaN,...,NaN,100,NaN,3.254679,NaN,NaN,NaN,NaN,NaN,NaN
2,THB03-32,Tom,NaN,2023-11-03 00:00:00,THB Project 2,NaN,NaN,NaN,NaN,NaN,...,NaN,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
3,AUF010,Kayleigh,NaN,2022-08-30 00:00:00,NaN,NaN,55.3,NaN,NaN,NaN,...,NaN,100,NaN,Missing data,NaN,NaN,NaN,NaN,NaN,NaN
4,AUF015,Kayleigh,NaN,2022-11-01 00:00:00,NaN,NaN,NaN,49,NaN,NaN,...,NaN,100.0,NaN,2.274751,Good,Mid,3,532,NaN,NaN

In [64]:
print(uv.columns)

Index(['Sample', 'Operator', 'Made?', 'Date ', ' Location of Data', 'ESBOA',
       'Epoxy:GPTA 75:25', 'Miramer PU2560', 'Photocryl DP408NT (40% DPGDA)',
       'Miramer U360NT',
       ...
       'GC1000Z', 'Total', 'Viscosity @30 °C', 'Acrylate density ',
       'Flexibility', 'Cure', 'WVP (1= good, 2= mid, 3= poor)',
       'WVP numbers (g/(m2/24hr)) -Pulse data', 'WVP number - in house data',
       'WVP in-house repeat of pulse films'],
      dtype='object', length=101)

This section contains columns that are unnecessary in the analysis process, including: 'Operator', 'Made?', 'Date ', ' Location of Data', 'Viscosity @30 °C', 'Acrylate density ', 'Flexibility', 'Cure', 'WVP (1= good, 2= mid, 3= poor)', 'WVP numbers (g/(m2/24hr)) -Pulse data', 'WVP number - in house data', 'WVP in-house repeat of pulse films'.

In [65]:
uv = uv.drop(columns=['Operator', 
                      'Made?', 
                      'Date ', 
                      ' Location of Data', 
                      'Viscosity @30 °C', 
                      'Acrylate density ', 
                      'Flexibility', 
                      'Cure', 
                      'WVP (1= good, 2= mid, 3= poor)', 
                      'WVP numbers (g/(m2/24hr)) -Pulse data', 
                      'WVP number - in house data', 
                      'WVP in-house repeat of pulse films'])

There are some blank spaces, all of which indicate that those chemicals are not in the formula, so they will be replaced with 0.

In [66]:
uv = uv.fillna(0)
uv.head(5)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_15020\3523612269.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  uv = uv.fillna(0)

,Sample,ESBOA,Epoxy:GPTA 75:25,Miramer PU2560,Photocryl DP408NT (40% DPGDA),Miramer U360NT,Miramer U3195NT,Miramer U3926NT,Miramer U3969NT,Miramer MU9800,...,HS417-1,Gasil HP33C,Span80,Synperonic 91/2.5 LQ,Agitan DF 6422,TEA,GC1100Y,Agisyn 008,GC1000Z,Total
0,50:50 ESBOA:PEG,47.5,0.0,0.0,0.0,0.0,0,0,0,0.0,...,0,0,0,0,0.0,0,0,0.0,0,100.0
1,THB03-03,66.5,0.0,0.0,0.0,0.0,0,0,0,0.0,...,0,0,0,0,0.0,0,0,0.0,0,100.0
2,THB03-32,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,...,0,0,0,0,0.0,0,0,0.0,0,1.0
3,AUF010,0.0,55.3,0.0,0.0,0.0,0,0,0,0.0,...,0,0,0,0,0.0,0,0,0.0,0,100.0
4,AUF015,0.0,0.0,49.0,0.0,0.0,0,0,0,0.0,...,0,0,0,0,0.0,0,0,0.0,0,100.0

Checking datatype

In [67]:
for col in uv.columns:
    if col == 'Sample':
        continue
    try:
        uv[col] = uv[col].astype('float64')
    except:
        pass

uv.dtypes[uv.dtypes != 'float64'].to_frame(name='dtype')

         dtype
Sample  object

The file has nothing unusual about its data type.

It was observed that some experiments in this column lacked complete data, resulting in a total percentage of ingredients ('Total') less than 100%. These will be removed.

In [68]:
check_0 = uv.copy()
cols_check = check_0.select_dtypes(include='number').columns
cols_check_sum = cols_check.drop('Total')
check_0['recalc_total'] = check_0[cols_check_sum].sum(axis=1)
check_0 = check_0[check_0['recalc_total'] < 100]
print(check_0[['recalc_total', 'Total']])
check_0

     recalc_total  Total
2             1.0    1.0
78           91.4   91.4
158          95.0   95.0

,Sample,ESBOA,Epoxy:GPTA 75:25,Miramer PU2560,Photocryl DP408NT (40% DPGDA),Miramer U360NT,Miramer U3195NT,Miramer U3926NT,Miramer U3969NT,Miramer MU9800,...,Gasil HP33C,Span80,Synperonic 91/2.5 LQ,Agitan DF 6422,TEA,GC1100Y,Agisyn 008,GC1000Z,Total,recalc_total
2,THB03-32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
78,AUF141,0.0,0.0,25.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,91.4,91.4
158,AUF221,37.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,95.0,95.0

In [69]:
uv = uv.drop(uv[uv['Total'] < 100].index)
uv

,Sample,ESBOA,Epoxy:GPTA 75:25,Miramer PU2560,Photocryl DP408NT (40% DPGDA),Miramer U360NT,Miramer U3195NT,Miramer U3926NT,Miramer U3969NT,Miramer MU9800,...,HS417-1,Gasil HP33C,Span80,Synperonic 91/2.5 LQ,Agitan DF 6422,TEA,GC1100Y,Agisyn 008,GC1000Z,Total
0,50:50 ESBOA:PEG,47.5,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,100.0
1,THB03-03,66.5,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,100.0
3,AUF010,0.0,55.3,0.0,0.00,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,100.0
4,AUF015,0.0,0.0,49.0,0.00,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,100.0
5,AUF042,20.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,100.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
318,AUF382,47.5,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,100.0
319,AUF383,47.5,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,100.0
320,AUF384,0.0,0.0,0.0,23.75,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,100.0
321,AUF385,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,100.0
322,AUF386,0.0,0.0,0.0,47.50,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,100.0

Export uv formulation data frame

## 4. CORE FORMULATIONS

In [70]:
print(core.columns)
print('-'*50)
core.head(20)

Index([' ', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25',
       'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29',
       'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33',
       'Unnamed: 34', 'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37',
       'Unnamed: 38', 'Unnamed: 39', 'Unnamed: 40', 'Unnamed: 41',
       'Unnamed: 42', 'Unnamed: 43', 'Unnamed: 44', 'Unnamed: 45',
       'Unnamed: 46', 'Unnamed: 47', 'Unnamed: 48', 'Unnamed: 49',
       'Unnamed: 50', 'Unnamed: 51', 'Unnamed: 52', 'Unnamed: 53',
       'Unnamed: 54', 'Unnamed: 55', 'Unnamed: 56', 'Unnamed: 57'],
      dtype='object')
--------------------------------------------------

,,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,Filter,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,Sample,NaN,RAD-C-0001,RAD-C-0002,RAD-C-0003,RAD-C-0004,RAD-C-0005,RAD-C-0006,...,RAD-C-0045,RAD-C-0046,RAD-C-0047,RAD-C-0048,RAD-C-0049,RAD-C-0050,RAD-C-0051,RAD-C-0052,RAD-C-0053,RAD-C-0054
7,NaN,NaN,Operator,NaN,Tom,Tom,Sian,Tom,Tom,Tom,...,LAD,THB,THB,LAD,LAD,LAD,LAD,LAD,LAD,LAD
8,NaN,NaN,Date,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2026-01-15 00:00:00,2026-01-15 00:00:00,2026-01-16 00:00:00,2026-01-16 00:00:00,2026-01-20 00:00:00,2026-01-21 00:00:00,2026-01-23 00:00:00,2026-01-28 00:00:00,2026-01-29 00:00:00,2026-01-29 00:00:00
9,NaN,NaN,OG name,NaN,OG core,94/6 (25%),94/6 (20%),95/5 (25%),95/5 (20%),96/4 (25%),...,Hydrolysed KE 1.25kg 25% batch,NaN,NaN,"OG with 1,5-PDO",20% HPC in 1:3 water:PEG200,Endpoint hyd HPC w/5.4% NaCl,Nisso 100k glycerol core,OG core with Nisso20% 100k,76 Nisso20% 100k / 17 / 7,76 Nisso30% 100k / 17 / 7
10,NaN,NaN,NaN,Klucel E,13.2,23.5,18.8,23.75,19,24,...,NaN,NaN,NaN,13.2,5,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,Klucel ELF,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,Nisso 40 K,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,33.2,33.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,Nisso 100 K,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,33.6,13.2,15.2,22.8
14,NaN,NaN,NaN,Hyd HPC unknown MW,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,Hyd HPC 7k,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,Hyd HPC 15k,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,Hyd HPC 20k,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,Hyd KE HPC 9k,NaN,NaN,NaN,NaN,NaN,NaN,...,23.64,NaN,NaN,NaN,NaN,18.78,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,Hyd KE HPC 5k,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Although the data file structure is similar to UV, the important information is contained in two independent columns, and we need to merge them into one column. <br>
<br>
Furthermore, this data file is clearer than the UV file, as the unimportant columns and rows all have one thing in common: they are 100% empty (except for the row containing 'Filter').

In [71]:
core = core.dropna(how='all')
core = core.dropna(axis=1, how='all')
core.head(5)

,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,...,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57
4,Filter,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Sample,NaN,RAD-C-0001,RAD-C-0002,RAD-C-0003,RAD-C-0004,RAD-C-0005,RAD-C-0006,RAD-C-0007,RAD-C-0008,...,RAD-C-0045,RAD-C-0046,RAD-C-0047,RAD-C-0048,RAD-C-0049,RAD-C-0050,RAD-C-0051,RAD-C-0052,RAD-C-0053,RAD-C-0054
7,Operator,NaN,Tom,Tom,Sian,Tom,Tom,Tom,Tom,Tom,...,LAD,THB,THB,LAD,LAD,LAD,LAD,LAD,LAD,LAD
8,Date,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2026-01-15 00:00:00,2026-01-15 00:00:00,2026-01-16 00:00:00,2026-01-16 00:00:00,2026-01-20 00:00:00,2026-01-21 00:00:00,2026-01-23 00:00:00,2026-01-28 00:00:00,2026-01-29 00:00:00,2026-01-29 00:00:00
9,OG name,NaN,OG core,94/6 (25%),94/6 (20%),95/5 (25%),95/5 (20%),96/4 (25%),96/4 (20%),93/7 (20%),...,Hydrolysed KE 1.25kg 25% batch,NaN,NaN,"OG with 1,5-PDO",20% HPC in 1:3 water:PEG200,Endpoint hyd HPC w/5.4% NaCl,Nisso 100k glycerol core,OG core with Nisso20% 100k,76 Nisso20% 100k / 17 / 7,76 Nisso30% 100k / 17 / 7

Rotate it and reset the index.

In [72]:
df = core.copy()

row_labels = df.iloc[:, :2].bfill(axis=1).iloc[:, 0]

data = df.iloc[:, 2:].copy()

data.index = row_labels

data = data.loc[data.index.notna()]

core = data.T.reset_index(drop=True)

core.columns.name = None

core.index.name = None

core.head(20)

,Filter,Sample,Operator,Date,OG name,Klucel E,Klucel ELF,Nisso 40 K,Nisso 100 K,Hyd HPC unknown MW,...,Klucel E,Klucel ELF,Nisso 40 K,Nisso 100 K,Hyd HPC unknown MW,Hyd HPC 7k,Hyd HPC 15k,Hyd HPC 20k,Hyd KE HPC 9k,Hyd KE HPC 5k
0,NaN,RAD-C-0001,Tom,NaN,OG core,13.2,NaN,NaN,NaN,NaN,...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,RAD-C-0002,Tom,NaN,94/6 (25%),23.5,NaN,NaN,NaN,NaN,...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,RAD-C-0003,Sian,NaN,94/6 (20%),18.8,NaN,NaN,NaN,NaN,...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,RAD-C-0004,Tom,NaN,95/5 (25%),23.75,NaN,NaN,NaN,NaN,...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,RAD-C-0005,Tom,NaN,95/5 (20%),19,NaN,NaN,NaN,NaN,...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,RAD-C-0006,Tom,NaN,96/4 (25%),24,NaN,NaN,NaN,NaN,...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,RAD-C-0007,Tom,NaN,96/4 (20%),NaN,19.2,NaN,NaN,NaN,...,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,RAD-C-0008,Tom,NaN,93/7 (20%),23.25,NaN,NaN,NaN,NaN,...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,RAD-C-0009,Luke,NaN,66/25.5/6.5/2 PEG550DMA,16.5,NaN,NaN,NaN,NaN,...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,RAD-C-0010,Luke,NaN,30/70 Glyc: HPC,17.5,NaN,NaN,NaN,NaN,...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,RAD-C-0011,Tom,NaN,2025-12-02 00:00:00,11.236,NaN,NaN,NaN,NaN,...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,RAD-C-0012,Luke,NaN,66/26/6/2% PEG550DMA,13.2,NaN,NaN,NaN,NaN,...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,RAD-C-0013,Luke,NaN,96/4 + 2% PEG550DMA,18.432,NaN,NaN,NaN,NaN,...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,RAD-C-0014,Luke,NaN,C12E6 in 96/4,18.8,NaN,NaN,NaN,NaN,...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,RAD-C-0015,Luke,NaN,C12E6 in OG core,13.2,NaN,NaN,NaN,NaN,...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,RAD-C-0016,Luke,NaN,66/27/7 + 2% PEG550DMA,12.942,NaN,NaN,NaN,NaN,...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,RAD-C-0017,Luke,NaN,66/27/7 + 1% PEG550DMA,13.07,NaN,NaN,NaN,NaN,...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,RAD-C-0018,Luke,NaN,66/27/7 + 0.5% PEG550DMA,13.134,NaN,NaN,NaN,NaN,...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,RAD-C-0019,Luke,NaN,66/27/7 + 0.1% PEG550DMA,13.186,NaN,NaN,NaN,NaN,...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,RAD-C-0020,Luke,NaN,0.0112% C12E6 in 94/6 (25%),23.5,NaN,NaN,NaN,NaN,...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [73]:
print(core.columns)

Index(['Filter', 'Sample', 'Operator', 'Date ', 'OG name', 'Klucel E',
       'Klucel ELF ', 'Nisso 40 K ', 'Nisso 100 K ', 'Hyd HPC unknown MW',
       'Hyd HPC 7k', 'Hyd HPC 15k', 'Hyd HPC 20k', 'Hyd KE HPC 9k',
       'Hyd KE HPC 5k', 'NaCl', 'CaCl2', 'PDO', 'Glycerol ', '1,5-PDO', 'MPG ',
       'C12E6', 'Water ', 'Go Water Solution (0.3%?)', 'PEG550DMA ', 'PEG200',
       'Total', 'Pass/ fail (homogeneous) ', 'Viscosity @25', 'LCST ',
       'Refractive index (%Brix)', 'DT ',
       'Concentration of HPC stock (wt% HPC)', 'Amount of stock added (wt%) ',
       'Klucel E', 'Klucel ELF ', 'Nisso 40 K ', 'Nisso 100 K ',
       'Hyd HPC unknown MW', 'Hyd HPC 7k', 'Hyd HPC 15k', 'Hyd HPC 20k',
       'Hyd KE HPC 9k', 'Hyd KE HPC 5k'],
      dtype='object')

This section contains columns that are unnecessary in the analysis process, including: 'Filter', 'Operator', 'Date ', 'OG name', 'Pass/ fail (homogeneous) ', 'Viscosity @25', 'LCST ', 'Refractive index (%Brix)', 'DT ', 'Concentration of HPC stock (wt% HPC)', 'Amount of stock added (wt%) ', 'Klucel E', 'Klucel ELF ', 'Nisso 40 K ', 'Nisso 100 K ', 'Hyd HPC unknown MW', 'Hyd HPC 7k', 'Hyd HPC 15k', 'Hyd HPC 20k', 'Hyd KE HPC 9k', 'Hyd KE HPC 5k'

In [74]:
core = core.drop(columns=['Filter','Operator', 
                          'Date ', 
                          'OG name',
                          'Pass/ fail (homogeneous) ', 
                          'Viscosity @25', 
                          'LCST ',
                          'Refractive index (%Brix)', 
                          'DT ',
                          'Concentration of HPC stock (wt% HPC)', 
                          'Amount of stock added (wt%) '])

# since the last 10 columns have the same names as the columns in the formula, iloc will be used to select all columns except the last 10.
core = core.iloc[:, :-10]

core.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 23 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Sample                     54 non-null     object
 1   Klucel E                   29 non-null     object
 2   Klucel ELF                 3 non-null      object
 3   Nisso 40 K                 4 non-null      object
 4   Nisso 100 K                4 non-null      object
 5   Hyd HPC unknown MW         2 non-null      object
 6   Hyd HPC 7k                 2 non-null      object
 7   Hyd HPC 15k                4 non-null      object
 8   Hyd HPC 20k                5 non-null      object
 9   Hyd KE HPC 9k              2 non-null      object
 10  Hyd KE HPC 5k              0 non-null      object
 11  NaCl                       51 non-null     object
 12  CaCl2                      1 non-null      object
 13  PDO                        16 non-null     object
 14  Glycerol                   10 non-null     object
 15  1,5-PDO                    1 non-null      object
 16  MPG                        1 non-null      object
 17  C12E6                      3 non-null      object
 18  Water                      54 non-null     object
 19  Go Water Solution (0.3%?)  4 non-null      object
 20  PEG550DMA                  8 non-null      object
 21  PEG200                     1 non-null      object
 22  Total                      54 non-null     object
dtypes: object(23)
memory usage: 9.8+ KB

There are some blank spaces, all of which indicate that those chemicals are not in the formula, so they will be replaced with 0.

In [75]:
core = core.fillna(0)
core.head(5)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_15020\2952262540.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  core = core.fillna(0)

,Sample,Klucel E,Klucel ELF,Nisso 40 K,Nisso 100 K,Hyd HPC unknown MW,Hyd HPC 7k,Hyd HPC 15k,Hyd HPC 20k,Hyd KE HPC 9k,...,PDO,Glycerol,"1,5-PDO",MPG,C12E6,Water,Go Water Solution (0.3%?),PEG550DMA,PEG200,Total
0,RAD-C-0001,13.20,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,...,27.0,0.0,0,0.0,0.0,52.8,0.0,0.0,0,100.0
1,RAD-C-0002,23.50,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,...,0.0,0.0,0,0.0,0.0,70.5,0.0,0.0,0,100.0
2,RAD-C-0003,18.80,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,...,0.0,0.0,0,0.0,0.0,75.2,0.0,0.0,0,100.0
3,RAD-C-0004,23.75,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,...,0.0,0.0,0,0.0,0.0,71.25,0.0,0.0,0,100.0
4,RAD-C-0005,19.00,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,...,0.0,0.0,0,0.0,0.0,76,0.0,0.0,0,100.0

Adjust data type

In [76]:
for col in core.columns:
    if col == 'Sample':
        continue
    try:
        core[col] = core[col].astype('float64')
    except:
        pass

core.dtypes.to_frame(name='dtype')

                             dtype
Sample                      object
Klucel E                   float64
Klucel ELF                 float64
Nisso 40 K                 float64
Nisso 100 K                float64
Hyd HPC unknown MW         float64
Hyd HPC 7k                 float64
Hyd HPC 15k                 object
Hyd HPC 20k                float64
Hyd KE HPC 9k              float64
Hyd KE HPC 5k              float64
NaCl                       float64
CaCl2                      float64
PDO                        float64
Glycerol                   float64
1,5-PDO                    float64
MPG                        float64
C12E6                      float64
Water                       object
Go Water Solution (0.3%?)  float64
PEG550DMA                  float64
PEG200                     float64
Total                      float64

Columns 'Hyd HPC 15k' and 'Water ' cannot be converted to float, so there may be incorrect values.

In [77]:
print(core['Hyd HPC 15k'].unique())
print('-'*50)
print(core['Water '].unique())

[0 19.050325 24.552 40 'x']
--------------------------------------------------
[52.8 70.5 75.2 71.25 76 72 76.8 69.75 49.5 52.5 52.81399999999999 73.728
 51.767999999999994 52.28 52.536 52.74400000000001 78.96 55.51200000000001
 77.868 75.609675 72.16799999999999 68.448 56.5 'y' 41.25 57.6 51.2 75.952
 56.856 76.3 52 52.2 0 62.4 51 70.92 49.8 50.4 15 75.82 60.8 53.2]

In [78]:
i = core[(core['Hyd HPC 15k'] == 'x') & (core['Water '] == 'y')]

There are two values, x and y, and both appear in the 'RAD-C-0033' form. This is a recording error, so this form will be dropped.

In [79]:
core = core.drop(i.index)

Re-adjust datatype

In [80]:
for col in core.columns:
    if col == 'Sample':
        continue
    try:
        core[col] = core[col].astype('float64')
    except:
        pass

core.dtypes.to_frame(name='dtype')

                             dtype
Sample                      object
Klucel E                   float64
Klucel ELF                 float64
Nisso 40 K                 float64
Nisso 100 K                float64
Hyd HPC unknown MW         float64
Hyd HPC 7k                 float64
Hyd HPC 15k                float64
Hyd HPC 20k                float64
Hyd KE HPC 9k              float64
Hyd KE HPC 5k              float64
NaCl                       float64
CaCl2                      float64
PDO                        float64
Glycerol                   float64
1,5-PDO                    float64
MPG                        float64
C12E6                      float64
Water                      float64
Go Water Solution (0.3%?)  float64
PEG550DMA                  float64
PEG200                     float64
Total                      float64

In [81]:
core[core['Total'] < 100]

,Sample,Klucel E,Klucel ELF,Nisso 40 K,Nisso 100 K,Hyd HPC unknown MW,Hyd HPC 7k,Hyd HPC 15k,Hyd HPC 20k,Hyd KE HPC 9k,...,PDO,Glycerol,"1,5-PDO",MPG,C12E6,Water,Go Water Solution (0.3%?),PEG550DMA,PEG200,Total
10,RAD-C-0011,11.236,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,...,28.08,0.0,0.0,0.0,0.0,52.814,0.0,0.0,0.0,100.0
29,RAD-C-0030,0.000,0.0,0.0,0.0,0.0,0.0,0.0,20.832,0.0,...,0.00,0.0,0.0,0.0,0.0,72.168,0.0,0.0,0.0,100.0
41,RAD-C-0042,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,...,0.00,12.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,13.0

Lines 10 and 29 both have a total of 100, but are still recorded as below 100%.

In [82]:
bad = core[core['Total'] < 100].copy()
print(bad['Total'].map(lambda x: f"{x:.15f}"))
print(bad.index)

10    99.999999999999986
29    99.999999999999986
41    13.000000000000000
Name: Total, dtype: object
Index([10, 29, 41], dtype='int64')

In [83]:
check = core.copy()
numeric_cols = check.select_dtypes(include='number').columns
cols_to_sum = numeric_cols.drop('Total')
check['recalc_total'] = check[cols_to_sum].sum(axis=1)
check = check[check['recalc_total'] < 100]
print(check[['recalc_total', 'Total']])
check

    recalc_total  Total
10    100.000000  100.0
17     99.998358  100.0
18     99.995934  100.0
29    100.000000  100.0
41     13.000000   13.0

,Sample,Klucel E,Klucel ELF,Nisso 40 K,Nisso 100 K,Hyd HPC unknown MW,Hyd HPC 7k,Hyd HPC 15k,Hyd HPC 20k,Hyd KE HPC 9k,...,Glycerol,"1,5-PDO",MPG,C12E6,Water,Go Water Solution (0.3%?),PEG550DMA,PEG200,Total,recalc_total
10,RAD-C-0011,11.236,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,...,0.0,0.0,0.0,0.0,52.814,0.0,0.000000,0.0,100.0,100.000000
17,RAD-C-0018,13.134,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,...,0.0,0.0,0.0,0.0,52.536,0.0,0.497512,0.0,100.0,99.998358
18,RAD-C-0019,13.186,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,...,0.0,0.0,0.0,0.0,52.744,0.0,0.099900,0.0,100.0,99.995934
29,RAD-C-0030,0.000,0.0,0.0,0.0,0.0,0.0,0.0,20.832,0.0,...,0.0,0.0,0.0,0.0,72.168,0.0,0.000000,0.0,100.0,100.000000
41,RAD-C-0042,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,...,12.0,0.0,0.0,0.0,0.000,0.0,0.000000,0.0,13.0,13.000000

After checking, this was found to be just a decimal error, so only the 'RAD-C-0042' sample was dropped.

In [84]:
core = core.drop(core[(core['Sample'] == 'RAD-C-0042')].index)
core

,Sample,Klucel E,Klucel ELF,Nisso 40 K,Nisso 100 K,Hyd HPC unknown MW,Hyd HPC 7k,Hyd HPC 15k,Hyd HPC 20k,Hyd KE HPC 9k,...,PDO,Glycerol,"1,5-PDO",MPG,C12E6,Water,Go Water Solution (0.3%?),PEG550DMA,PEG200,Total
0,RAD-C-0001,13.200,0.0,0.0,0.0,0.00,0.00,0.000000,0.000,0.00,...,27.000000,0.000000,0.0,0.000000,0.0000,52.800000,0.0,0.000000,0.0,100.0
1,RAD-C-0002,23.500,0.0,0.0,0.0,0.00,0.00,0.000000,0.000,0.00,...,0.000000,0.000000,0.0,0.000000,0.0000,70.500000,0.0,0.000000,0.0,100.0
2,RAD-C-0003,18.800,0.0,0.0,0.0,0.00,0.00,0.000000,0.000,0.00,...,0.000000,0.000000,0.0,0.000000,0.0000,75.200000,0.0,0.000000,0.0,100.0
3,RAD-C-0004,23.750,0.0,0.0,0.0,0.00,0.00,0.000000,0.000,0.00,...,0.000000,0.000000,0.0,0.000000,0.0000,71.250000,0.0,0.000000,0.0,100.0
4,RAD-C-0005,19.000,0.0,0.0,0.0,0.00,0.00,0.000000,0.000,0.00,...,0.000000,0.000000,0.0,0.000000,0.0000,76.000000,0.0,0.000000,0.0,100.0
5,RAD-C-0006,24.000,0.0,0.0,0.0,0.00,0.00,0.000000,0.000,0.00,...,0.000000,0.000000,0.0,0.000000,0.0000,72.000000,0.0,0.000000,0.0,100.0
6,RAD-C-0007,0.000,19.2,0.0,0.0,0.00,0.00,0.000000,0.000,0.00,...,0.000000,0.000000,0.0,0.000000,0.0000,76.800000,0.0,0.000000,0.0,100.0
7,RAD-C-0008,23.250,0.0,0.0,0.0,0.00,0.00,0.000000,0.000,0.00,...,0.000000,0.000000,0.0,0.000000,0.0000,69.750000,0.0,0.000000,0.0,100.0
8,RAD-C-0009,16.500,0.0,0.0,0.0,0.00,0.00,0.000000,0.000,0.00,...,25.500000,0.000000,0.0,0.000000,0.0000,49.500000,0.0,2.000000,0.0,100.0
9,RAD-C-0010,17.500,0.0,0.0,0.0,0.00,0.00,0.000000,0.000,0.00,...,0.000000,30.000000,0.0,0.000000,0.0000,52.500000,0.0,0.000000,0.0,100.0
10,RAD-C-0011,11.236,0.0,0.0,0.0,0.00,0.00,0.000000,0.000,0.00,...,28.080000,0.000000,0.0,0.000000,0.0000,52.814000,0.0,0.000000,0.0,100.0
11,RAD-C-0012,13.200,0.0,0.0,0.0,0.00,0.00,0.000000,0.000,0.00,...,26.000000,0.000000,0.0,0.000000,0.0000,52.800000,0.0,2.000000,0.0,100.0
12,RAD-C-0013,18.432,0.0,0.0,0.0,0.00,0.00,0.000000,0.000,0.00,...,0.000000,0.000000,0.0,0.000000,0.0000,73.728000,0.0,1.960784,0.0,100.0
13,RAD-C-0014,18.800,0.0,0.0,0.0,0.00,0.00,0.000000,0.000,0.00,...,0.000000,0.000000,0.0,0.000000,0.0112,75.200000,0.0,0.000000,0.0,100.0
14,RAD-C-0015,13.200,0.0,0.0,0.0,0.00,0.00,0.000000,0.000,0.00,...,27.000000,0.000000,0.0,0.000000,0.0112,52.800000,0.0,0.000000,0.0,100.0
15,RAD-C-0016,12.942,0.0,0.0,0.0,0.00,0.00,0.000000,0.000,0.00,...,26.470588,0.000000,0.0,0.000000,0.0000,51.768000,0.0,1.960784,0.0,100.0
16,RAD-C-0017,13.070,0.0,0.0,0.0,0.00,0.00,0.000000,0.000,0.00,...,26.732673,0.000000,0.0,0.000000,0.0000,52.280000,0.0,0.990099,0.0,100.0
17,RAD-C-0018,13.134,0.0,0.0,0.0,0.00,0.00,0.000000,0.000,0.00,...,26.865672,0.000000,0.0,0.000000,0.0000,52.536000,0.0,0.497512,0.0,100.0
18,RAD-C-0019,13.186,0.0,0.0,0.0,0.00,0.00,0.000000,0.000,0.00,...,26.973027,0.000000,0.0,0.000000,0.0000,52.744000,0.0,0.099900,0.0,100.0
19,RAD-C-0020,23.500,0.0,0.0,0.0,0.00,0.00,0.000000,0.000,0.00,...,0.000000,0.000000,0.0,0.000000,0.0112,70.500000,0.0,0.000000,0.0,100.0
20,RAD-C-0021,15.040,0.0,0.0,0.0,0.00,0.00,0.000000,0.000,0.00,...,0.000000,0.000000,0.0,0.000000,0.0000,78.960000,0.0,0.000000,0.0,100.0
21,RAD-C-0022,0.000,0.0,0.0,0.0,15.04,0.00,0.000000,0.000,0.00,...,0.000000,0.000000,0.0,0.000000,0.0000,78.960000,0.0,0.000000,0.0,100.0
22,RAD-C-0023,18.504,0.0,0.0,0.0,0.00,0.00,0.000000,0.000,0.00,...,21.259843,0.000000,0.0,0.000000,0.0000,55.512000,0.0,0.000000,0.0,100.0
23,RAD-C-0024,18.504,0.0,0.0,0.0,0.00,0.00,0.000000,0.000,0.00,...,0.000000,0.000000,0.0,21.259843,0.0000,55.512000,0.0,0.000000,0.0,100.0
24,RAD-C-0025,18.504,0.0,0.0,0.0,0.00,0.00,0.000000,0.000,0.00,...,0.000000,21.259843,0.0,0.000000,0.0000,55.512000,0.0,0.000000,0.0,100.0
25,RAD-C-0026,0.000,0.0,0.0,0.0,15.04,0.00,0.000000,0.000,0.00,...,0.000000,0.000000,0.0,0.000000,0.0000,78.960000,0.0,0.000000,0.0,100.0
26,RAD-C-0027,0.000,0.0,0.0,0.0,0.00,15.04,0.000000,0.000,0.00,...,0.000000,0.000000,0.0,0.000000,0.0000,78.960000,0.0,0.000000,0.0,100.0
27,RAD-C-0028,0.000,0.0,0.0,0.0,0.00,0.00,0.000000,16.632,0.00,...,0.000000,0.000000,0.0,0.000000,0.0000,77.868000,0.0,0.000000,0.0,100.0
28,RAD-C-0029,0.000,0.0,0.0,0.0,0.00,0.00,19.050325,0.000,0.00,...,0.000000,0.000000,0.0,0.000000,0.0000,75.609675,0.0,0.000000,0.0,100.0
29,RAD-C-0030,0.000,0.0,0.0,0.0,0.00,0.00,0.000000,20.832,0.00,...,0.000000,0.000000,0.0,0.000000,0.0000,72.168000,0.0,0.000000,0.0,100.0
30,RAD-C-0031,0.000,0.0,0.0,0.0,0.00,0.00,24.552000,0.000,0.00,...,0.000000,0.000000,0.0,0.000000,0.0000,68.448000,0.0,0.000000,0.0,100.0
31,RAD-C-0032,0.000,0.0,0.0,0.0,0.00,0.00,40.000000,0.000,0.00,...,0.000000,0.000000,0.0,0.000000,0.0000,56.500000,0.0,0.000000,0.0,100.0
33,RAD-C-0034,13.750,0.0,0.0,0.0,0.00,0.00,0.000000,0.000,0.00,...,27.000000,0.000000,0.0,0.000000,0.0000,41.250000,11.0,0.000000,0.0,100.0
34,RAD-C-0035,19.200,0.0,0.0,0.0,0.00,0.00,0.000000,0.000,0.00,...,0.000000,0.000000,0.0,0.000000,0.0000,57.600000,19.2,0.000000,0.0,100.0
35,RAD-C-0036,12.800,0.0,0.0,0.0,0.00,0.00,0.000000,0.000,0.00,...,24.000000,0.000000,0.0,0.000000,0.0000,51.200000,0.0,2.000000,0.0,100.0
36,RAD-C-0037,0.000,0.0,0.0,0.0,0.00,0.00,0.000000,18.048,0.00,...,0.000000,0.000000,0.0,0.000000,0.0000,75.952000,0.0,0.000000,0.0,100.0
37,RAD-C-0038,0.000,0.0,0.0,0.0,0.00,0.00,0.000000,12.144,0.00,...,27.000000,0.000000,0.0,0.000000,0.0000,56.856000,0.0,0.000000,0.0,100.0
38,RAD-C-0039,0.000,13.5,0.0,0.0,0.00,0.00,0.000000,6.500,0.00,...,0.000000,0.000000,0.0,0.000000,0.0000,76.300000,0.0,0.000000,0.0,100.0
39,RAD-C-0040,0.000,0.0,0.0,0.0,0.00,35.00,0.000000,0.000,0.00,...,0.000000,12.000000,0.0,0.000000,0.0000,52.000000,0.0,0.000000,0.0,100.0
40,RAD-C-0041,0.000,34.8,0.0,0.0,0.00,0.00,0.000000,0.000,0.00,...,0.000000,12.000000,0.0,0.000000,0.0000,52.200000,0.0,0.000000,0.0,100.0
42,RAD-C-0043,15.600,0.0,0.0,0.0,0.00,0.00,0.000000,0.000,0.00,...,0.000000,20.000000,0.0,0.000000,0.0000,62.400000,0.0,0.000000,0.0,100.0
43,RAD-C-0044,0.000,0.0,34.0,0.0,0.00,0.00,0.000000,0.000,0.00,...,0.000000,12.000000,0.0,0.000000,0.0000,51.000000,0.0,0.000000,0.0,100.0
44,RAD-C-0045,0.000,0.0,0.0,0.0,0.00,0.00,0.000000,0.000,23.64,...,0.000000,0.000000,0.0,0.000000,0.0000,70.920000,0.0,0.000000,0.0,100.0
45,RAD-C-0046,0.000,0.0,33.2,0.0,0.00,0.00,0.000000,0.000,0.00,...,0.000000,12.000000,0.0,0.000000,0.0000,49.800000,0.0,0.000000,0.0,100.0
46,RAD-C-0047,0.000,0.0,33.6,0.0,0.00,0.00,0.000000,0.000,0.00,...,0.000000,12.000000,0.0,0.000000,0.0000,50.400000,0.0,0.000000,0.0,100.0
47,RAD-C-0048,13.200,0.0,0.0,0.0,0.00,0.00,0.000000,0.000,0.00,...,0.000000,0.000000,27.0,0.000000,0.0000,52.800000,0.0,0.000000,0.0,100.0
48,RAD-C-0049,5.000,0.0,0.0,0.0,0.00,0.00,0.000000,0.000,0.00,...,0.000000,0.000000,0.0,0.000000,0.0000,15.000000,20.0,0.000000,60.0,100.0
49,RAD-C-0050,0.000,0.0,0.0,0.0,0.00,0.00,0.000000,0.000,18.78,...,0.000000,0.000000,0.0,0.000000,0.0000,75.820000,0.0,0.000000,0.0,100.0
50,RAD-C-0051,0.000,0.0,0.0,33.6,0.00,0.00,0.000000,0.000,0.00,...,0.000000,7.500000,0.0,0.000000,0.0000,50.400000,4.5,0.000000,0.0,100.0
51,RAD-C-0052,0.000,0.0,0.0,13.2,0.00,0.00,0.000000,0.000,0.00,...,27.000000,0.000000,0.0,0.000000,0.0000,52.800000,0.0,0.000000,0.0,100.0
52,RAD-C-0053,0.000,0.0,0.0,15.2,0.00,0.00,0.000000,0.000,0.00,...,17.000000,0.000000,0.0,0.000000,0.0000,60.800000,0.0,0.000000,0.0,100.0
53,RAD-C-0054,0.000,0.0,0.0,22.8,0.00,0.00,0.000000,0.000,0.00,...,17.000000,0.000000,0.0,0.000000,0.0000,53.200000,0.0,0.000000,0.0,100.0

## 5. OUTER FORMULATION

In [85]:
print(outer.columns)
print('-'*50)
outer.head(20)

Index([' ', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25',
       'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29',
       'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33',
       'Unnamed: 34', 'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37',
       'Unnamed: 38', 'Unnamed: 39', 'Unnamed: 40', 'Unnamed: 41',
       'Unnamed: 42', 'Unnamed: 43', 'Unnamed: 44', 'Unnamed: 45',
       'Unnamed: 46', 'Unnamed: 47', 'Unnamed: 48', 'Unnamed: 49',
       'Unnamed: 50', 'Unnamed: 51', 'Unnamed: 52', 'Unnamed: 53',
       'Unnamed: 54', 'Unnamed: 55', 'Unnamed: 56', 'Unnamed: 57'],
      dtype='object')
--------------------------------------------------

,,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,Filter,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,Sample,NaN,2.25/38G/7,4.5/14.7P/4,2.25/38P/7,2.25/38M/7,4.5/14.7M/4,4.5/19M/6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,Operator,NaN,Kayleigh,Luke,Kayleigh,Luke,Luke,Luke,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,Date,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,OG name,NaN,AXF-1 outer,96/4 Outer,PDO Outer,MPG Outer,96/4 Outer,94/6 Outer,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaCl,7,4,7,7,4,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,Glycerol,38,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,PDO,NaN,14.7,38,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,MPG,NaN,NaN,NaN,38,14.7,19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,Sugar,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,PVA (10% in water),2.25,4.5,2.25,2.25,4.5,4.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,Water,52.75,76.8,52.75,52.75,76.8,70.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Its structure is exactly the same as a 'Core' file, so the operation is the same.

In [86]:
outer = outer.dropna(how='all')
outer = outer.dropna(axis=1, how='all')
outer

,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
4,Filter,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Sample,NaN,2.25/38G/7,4.5/14.7P/4,2.25/38P/7,2.25/38M/7,4.5/14.7M/4,4.5/19M/6,2.25/27P/11S/7
7,Operator,NaN,Kayleigh,Luke,Kayleigh,Luke,Luke,Luke,Luke
8,Date,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,OG name,NaN,AXF-1 outer,96/4 Outer,PDO Outer,MPG Outer,96/4 Outer,94/6 Outer,Sugar Outer
10,NaN,NaCl,7,4,7,7,4,6,7
12,NaN,Glycerol,38,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,PDO,NaN,14.7,38,NaN,NaN,NaN,27
14,NaN,MPG,NaN,NaN,NaN,38,14.7,19,NaN
15,NaN,Sugar,NaN,NaN,NaN,NaN,NaN,NaN,11
16,NaN,PVA (10% in water),2.25,4.5,2.25,2.25,4.5,4.5,2.25
18,NaN,Water,52.75,76.8,52.75,52.75,76.8,70.5,52.75

In [87]:
df = outer.copy()

row_labels = df.iloc[:, :2].bfill(axis=1).iloc[:, 0]

data = df.iloc[:, 2:].copy()

data.index = row_labels

data = data.loc[data.index.notna()]

outer = data.T.reset_index(drop=True)

outer.columns.name = None

outer.index.name = None

outer

,Filter,Sample,Operator,Date,OG name,NaCl,Glycerol,PDO,MPG,Sugar,PVA (10% in water),Water
0,NaN,2.25/38G/7,Kayleigh,NaN,AXF-1 outer,7,38,NaN,NaN,NaN,2.25,52.75
1,NaN,4.5/14.7P/4,Luke,NaN,96/4 Outer,4,NaN,14.7,NaN,NaN,4.5,76.8
2,NaN,2.25/38P/7,Kayleigh,NaN,PDO Outer,7,NaN,38,NaN,NaN,2.25,52.75
3,NaN,2.25/38M/7,Luke,NaN,MPG Outer,7,NaN,NaN,38,NaN,2.25,52.75
4,NaN,4.5/14.7M/4,Luke,NaN,96/4 Outer,4,NaN,NaN,14.7,NaN,4.5,76.8
5,NaN,4.5/19M/6,Luke,NaN,94/6 Outer,6,NaN,NaN,19,NaN,4.5,70.5
6,NaN,2.25/27P/11S/7,Luke,NaN,Sugar Outer,7,NaN,27,NaN,11,2.25,52.75

In [88]:
outer.columns

Index(['Filter', 'Sample', 'Operator', 'Date ', 'OG name', 'NaCl', 'Glycerol',
       'PDO', 'MPG', 'Sugar', 'PVA (10% in water)', 'Water'],
      dtype='object')

In [89]:
outer = outer.drop(columns=['Filter','Date ', 'Operator', 'OG name'])
outer = outer.fillna(0)
outer

           Sample NaCl Glycerol   PDO   MPG Sugar PVA (10% in water)  Water
0      2.25/38G/7    7       38     0     0     0               2.25  52.75
1     4.5/14.7P/4    4        0  14.7     0     0                4.5   76.8
2      2.25/38P/7    7        0    38     0     0               2.25  52.75
3      2.25/38M/7    7        0     0    38     0               2.25  52.75
4     4.5/14.7M/4    4        0     0  14.7     0                4.5   76.8
5       4.5/19M/6    6        0     0    19     0                4.5   70.5
6  2.25/27P/11S/7    7        0    27     0    11               2.25  52.75

In [90]:
outer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Sample              7 non-null      object
 1   NaCl                7 non-null      object
 2   Glycerol            7 non-null      object
 3   PDO                 7 non-null      object
 4   MPG                 7 non-null      object
 5   Sugar               7 non-null      object
 6   PVA (10% in water)  7 non-null      object
 7   Water               7 non-null      object
dtypes: object(8)
memory usage: 580.0+ bytes

In [91]:
for col in outer.columns:
    if col == 'Sample':
        continue
    try:
        outer[col] = outer[col].astype('float64')
    except:
        pass

outer.dtypes.to_frame(name='dtype')

                      dtype
Sample               object
NaCl                float64
Glycerol            float64
PDO                 float64
MPG                 float64
Sugar               float64
PVA (10% in water)  float64
Water               float64

check the total percentage of substances

In [92]:
check_1 = outer.copy()
numeric_cols_check = check_1.select_dtypes(include='number').columns
check_1['total'] = check_1[numeric_cols_check].sum(axis=1)
check_1 = check_1[check_1['total'] < 100]
print(check_1['total'])
check_1

Series([], Name: total, dtype: float64)

Empty DataFrame
Columns: [Sample, NaCl, Glycerol, PDO, MPG, Sugar, PVA (10% in water), Water, total]
Index: []

The file contains nothing unusual.

## 6. CORE BATCH

In [93]:
core_batch

,Records of QC tests carried out on batches of core made,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Old name,Formulation,Batch Number,Date,Batch Quantity (kg),Viscosity (cP) @ RT 5 RPM,Visco (s DIN4),Viscosity (cP) @ RT 20 RPM,Viscosity temperature (°C),Starting LCST temperature (°C),Finish LCST temperature (°C),Osmolarity @ 0.25x,QC operator initials,Pass/Fail,Comments
2,KE core 02-12 (AXF-1),RAD-C-0011,BNC00001,2024-03-25 00:00:00,2,NaN,308,NaN,NaN,18,18,1278,KLM,Pass,NaN
3,KE core 02-12 (Telos),RAD-C-0011,BNC00002,2024-04-02 00:00:00,0.774,NaN,53,NaN,NaN,13,NaN,1800,KLM,Pass,NaN
4,KE core 02-12T,RAD-C-0011,BNC00003,2024-04-09 00:00:00,0.89,NaN,79.27,NaN,NaN,14.5,NaN,1745,LAD,Pass,"Osmolarity high, +0.5% salt"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114,96.5/3.5 (<40% 15k),RAD-C-0032,BNC00113,2025-12-02 00:00:00,0.06,9288,NaN,NaN,19.1,NaN,NaN,NaN,NaN,NaN,NaN
115,94/6 (20%),RAD-C-0003,BNC00114,2025-12-02 00:00:00,0.6,16510,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
116,95.4/4.6 (x% 15k),RAD-C-0033,BNC00115,2025-11-01 00:00:00,0.06,336,NaN,NaN,19.6,NaN,NaN,NaN,NaN,NaN,[HPC] is unknown
117,core 02-12,RAD-C-0011,BNC00116,2026-01-27 00:00:00,0.015,1536,NaN,NaN,19.5,NaN,NaN,NaN,NaN,NaN,NaN
118,Hydrolysed HPC 9k (1.25kg batch),RAD-C-0045,BNC00117,15/1/2026,1.35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [94]:
new_header = core_batch.iloc[1]

core_batch = core_batch.iloc[2:].copy()

core_batch.columns = new_header

core_batch = core_batch.reset_index(drop=True)

core_batch.columns.name = None

core_batch

,Old name,Formulation,Batch Number,Date,Batch Quantity (kg),Viscosity (cP) @ RT 5 RPM,Visco (s DIN4),Viscosity (cP) @ RT 20 RPM,Viscosity temperature (°C),Starting LCST temperature (°C),Finish LCST temperature (°C),Osmolarity @ 0.25x,QC operator initials,Pass/Fail,Comments
0,KE core 02-12 (AXF-1),RAD-C-0011,BNC00001,2024-03-25 00:00:00,2,NaN,308,NaN,NaN,18,18,1278,KLM,Pass,NaN
1,KE core 02-12 (Telos),RAD-C-0011,BNC00002,2024-04-02 00:00:00,0.774,NaN,53,NaN,NaN,13,NaN,1800,KLM,Pass,NaN
2,KE core 02-12T,RAD-C-0011,BNC00003,2024-04-09 00:00:00,0.89,NaN,79.27,NaN,NaN,14.5,NaN,1745,LAD,Pass,"Osmolarity high, +0.5% salt"
3,KE core 02-12T,RAD-C-0011,BNC00004,2024-04-16 00:00:00,1.06,NaN,62,NaN,NaN,15,NaN,1868,LAD,Pass,NaN
4,KE core 02-12A,RAD-C-0011,BNC00005,2024-04-23 00:00:00,0.8,NaN,182,NaN,NaN,15.4,18.2,1875,THB,Pass,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112,96.5/3.5 (<40% 15k),RAD-C-0032,BNC00113,2025-12-02 00:00:00,0.06,9288,NaN,NaN,19.1,NaN,NaN,NaN,NaN,NaN,NaN
113,94/6 (20%),RAD-C-0003,BNC00114,2025-12-02 00:00:00,0.6,16510,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
114,95.4/4.6 (x% 15k),RAD-C-0033,BNC00115,2025-11-01 00:00:00,0.06,336,NaN,NaN,19.6,NaN,NaN,NaN,NaN,NaN,[HPC] is unknown
115,core 02-12,RAD-C-0011,BNC00116,2026-01-27 00:00:00,0.015,1536,NaN,NaN,19.5,NaN,NaN,NaN,NaN,NaN,NaN
116,Hydrolysed HPC 9k (1.25kg batch),RAD-C-0045,BNC00117,15/1/2026,1.35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [95]:
core_batch.columns

Index(['Old name', 'Formulation', 'Batch Number ', 'Date',
       'Batch Quantity (kg)', 'Viscosity (cP) @ RT 5 RPM', 'Visco (s DIN4)  ',
       'Viscosity (cP) @ RT 20 RPM', 'Viscosity temperature (°C)',
       'Starting LCST temperature (°C) ', 'Finish LCST temperature (°C) ',
       'Osmolarity @ 0.25x ', 'QC operator initials', 'Pass/Fail', 'Comments'],
      dtype='object')

In [96]:
core_batch = core_batch.drop(columns=['Old name','Date','Batch Quantity (kg)','Viscosity (cP) @ RT 5 RPM', 'Visco (s DIN4)  ',
       'Viscosity (cP) @ RT 20 RPM', 'Viscosity temperature (°C)',
       'Starting LCST temperature (°C) ', 'Finish LCST temperature (°C) ',
       'Osmolarity @ 0.25x ', 'QC operator initials', 'Pass/Fail', 'Comments'])
core_batch.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 117 entries, 0 to 116
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Formulation    110 non-null    object
 1   Batch Number   117 non-null    object
dtypes: object(2)
memory usage: 2.0+ KB

It was discovered that some batches lacked information about the formulation.

In [97]:
core_batch[core_batch.isna().any(axis=1)]

   Formulation Batch Number
24         NaN      BNC00025
25         NaN      BNC00026
26         NaN      BNC00027
61         NaN      BNC00062
66         NaN      BNC00067
76         NaN      BNC00077
78         NaN      BNC00079

In [98]:
core_batch =  core_batch.dropna()
core_batch.info()

<class 'pandas.core.frame.DataFrame'>
Index: 110 entries, 0 to 116
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Formulation    110 non-null    object
 1   Batch Number   110 non-null    object
dtypes: object(2)
memory usage: 2.6+ KB

## 7. UV BATCH

In [99]:
uv_batch

,Formulation,Batch Number,Date made,Batch Quantity (kg),Viscosity @ RT RPM,Temp (°C) at visco measurement,Cure,QC operator initials,QC addition,Pass/Fail,Comments
0,AUF069,BNU00001,2024-04-26 00:00:00,1.000,185.0,NaN,Y,KLM,NaN,Pass,NaN
1,AUF069,BNU00002,2024-04-30 00:00:00,5.000,206.0,NaN,Y,KLM,NaN,Pass,NaN
2,AUF069,BNU00003,2024-05-08 00:00:00,1.000,230.0,NaN,Y,KLM,0.7% TPGDA,Pass,NaN
3,AUF069,BNU00004,2024-05-16 00:00:00,5.500,242.0,NaN,Y,KLM,NaN,NaN,NaN
4,Adjusted UV for Telos from AXF,BNU00005,2024-05-31 00:00:00,1.000,215.0,NaN,Y,KLM,NaN,Pass,NaN
...,...,...,...,...,...,...,...,...,...,...,...
172,AUF324,BNU00172,2025-12-22 00:00:00,0.235,424.8,18.9,Y,LAD,NaN,NaN,160g fresh + 75g BNU142
173,AUF103,BNU00173,2025-12-23 00:00:00,0.150,288.0,21.5,Y,KLM,NaN,NaN,NaN
174,AUF279,BNU00174,19/01/2026,0.150,357.6,19.6,Y,KLM,NaN,NaN,NaN
175,AUF274,BNU00175,19/01/2026,0.150,330.0,19.7,Y,KLM,NaN,NaN,NaN
176,AUF285,BNU00176,29/01/2026,0.150,342.0,19.5,Y,MH/KLM,NaN,NaN,NaN

In [100]:
uv_batch.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 177 entries, 0 to 176
Data columns (total 11 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Formulation                      177 non-null    object
 1   Batch Number                     177 non-null    object
 2   Date made                        169 non-null    object
 3   Batch Quantity (kg)              177 non-null    float64
 4   Viscosity @ RT RPM               164 non-null    float64
 5   Temp (°C) at visco measurement   84 non-null     float64
 6   Cure                             127 non-null    object
 7   QC operator initials             129 non-null    object
 8   QC addition                      1 non-null      object
 9   Pass/Fail                        12 non-null     object
 10  Comments                         20 non-null     object
dtypes: float64(3), object(8)
memory usage: 15.3+ KB

In [101]:
uv_batch.columns

Index(['Formulation', 'Batch Number ', 'Date made ', 'Batch Quantity (kg)',
       'Viscosity @ RT RPM', 'Temp (°C) at visco measurement ', 'Cure ',
       'QC operator initials', 'QC addition ', 'Pass/Fail', 'Comments'],
      dtype='object')

In [102]:
uv_batch = uv_batch.drop(columns=['Date made ', 'Batch Quantity (kg)', 'Viscosity @ RT RPM', 'Temp (°C) at visco measurement ', 'Cure ',
       'QC operator initials', 'QC addition ', 'Pass/Fail', 'Comments'])
uv_batch.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 177 entries, 0 to 176
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Formulation    177 non-null    object
 1   Batch Number   177 non-null    object
dtypes: object(2)
memory usage: 2.9+ KB

No abnormalities were observed.

## 8. OUTER BATCH

In [103]:
outer_batch

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,0.838889,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Formulation,Batch Number,Date made,Batch Quantity (kg),Viscosity @ RT (t = 10mins) 100 RPM,Osmolarity @ 0.25x,Temp @ visco (°C),QC operator initials,QC addition,Pass/Fail,Comments
2,NaN,Telos outer (rusty PVA),BNO00001,2024-03-27 00:00:00,20,20 cp/ 15s (DIN4),1022,NaN,KLM,NaN,Pass,NaN
3,NaN,AXF_1 outer,BNO00002,2024-03-28 00:00:00,20,8,1000,NaN,KLM,NaN,Fail,NaN
4,NaN,Telos outer,BNO00003,2024-04-02 00:00:00,5,20.8,1034,NaN,KLM,NaN,Pass,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
252,NaN,2.25/11.7G/32.5S/1,BNO00250,2026-01-05 00:00:00,0.2,18,NaN,18.4,MH,NaN,NaN,NaN
253,NaN,2.25/27P/11S/7,BNO00251,2026-01-08 00:00:00,1,14.4,NaN,18.4,MH,NaN,NaN,NaN
254,NaN,2.25/27P/11S/7,BNO00252,22/01/2026,1,13.2,NaN,19.4,MH,NaN,NaN,NaN
255,NaN,2.25/28.08P/8.99S/7.87,BNO00253,2026-01-28 00:00:00,0.2,14.4,NaN,20.3,MH,NaN,NaN,NaN
256,NaN,2.25/27P/11S/7,BNO00254,2026-05-02 00:00:00,1,14.4,NaN,22.6,MH,NaN,NaN,NaN

In [104]:
new_head = outer_batch.iloc[1]

outer_batch =  outer_batch.iloc[2:].copy()

outer_batch.columns = new_head

outer_batch = outer_batch.reset_index(drop=True)

outer_batch.columns.name = None

outer_batch

,NaN,Formulation,Batch Number,Date made,Batch Quantity (kg),Viscosity @ RT (t = 10mins) 100 RPM,Osmolarity @ 0.25x,Temp @ visco (°C),QC operator initials,QC addition,Pass/Fail,Comments
0,NaN,Telos outer (rusty PVA),BNO00001,2024-03-27 00:00:00,20,20 cp/ 15s (DIN4),1022,NaN,KLM,NaN,Pass,NaN
1,NaN,AXF_1 outer,BNO00002,2024-03-28 00:00:00,20,8,1000,NaN,KLM,NaN,Fail,NaN
2,NaN,Telos outer,BNO00003,2024-04-02 00:00:00,5,20.8,1034,NaN,KLM,NaN,Pass,NaN
3,NaN,AXF_1 outer,BNO00004,2024-04-02 00:00:00,20,12s (DIN4),1026,NaN,KLM/LAD,NaN,Pass,NaN
4,NaN,Telos outer,BNO00005,2024-04-03 00:00:00,2,14s (DIN4),1148.666667,NaN,KLM/LAD,NaN,Pass,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
250,NaN,2.25/11.7G/32.5S/1,BNO00250,2026-01-05 00:00:00,0.2,18,NaN,18.4,MH,NaN,NaN,NaN
251,NaN,2.25/27P/11S/7,BNO00251,2026-01-08 00:00:00,1,14.4,NaN,18.4,MH,NaN,NaN,NaN
252,NaN,2.25/27P/11S/7,BNO00252,22/01/2026,1,13.2,NaN,19.4,MH,NaN,NaN,NaN
253,NaN,2.25/28.08P/8.99S/7.87,BNO00253,2026-01-28 00:00:00,0.2,14.4,NaN,20.3,MH,NaN,NaN,NaN
254,NaN,2.25/27P/11S/7,BNO00254,2026-05-02 00:00:00,1,14.4,NaN,22.6,MH,NaN,NaN,NaN

In [105]:
outer_batch.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 255 entries, 0 to 254
Data columns (total 12 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   nan                                  0 non-null      float64
 1   Formulation                          255 non-null    object
 2   Batch Number                         254 non-null    object
 3   Date made                            255 non-null    object
 4   Batch Quantity (kg)                  252 non-null    object
 5   Viscosity @ RT (t = 10mins) 100 RPM  232 non-null    object
 6   Osmolarity @ 0.25x                   57 non-null     object
 7   Temp @ visco (°C)                    55 non-null     object
 8   QC operator initials                 221 non-null    object
 9   QC addition                          1 non-null      object
 10  Pass/Fail                            30 non-null     object
 11  Comments                             14 non-null     object
dtypes: float64(1), object(11)
memory usage: 24.0+ KB

In [106]:
outer_batch.columns

Index([                                  nan,
                               'Formulation',
                             'Batch Number ',
                                'Date made ',
                       'Batch Quantity (kg)',
       'Viscosity @ RT (t = 10mins) 100 RPM',
                       'Osmolarity @ 0.25x ',
                         'Temp @ visco (°C)',
                      'QC operator initials',
                              'QC addition ',
                                 'Pass/Fail',
                                  'Comments'],
      dtype='object')

In [107]:
outer_batch = outer_batch.drop(columns=[outer_batch.columns[0], 'Date made ','Batch Quantity (kg)',
       'Viscosity @ RT (t = 10mins) 100 RPM',
                       'Osmolarity @ 0.25x ',
                         'Temp @ visco (°C)',
                      'QC operator initials',
                              'QC addition ',
                                 'Pass/Fail',
                                  'Comments'])

In [108]:
outer_batch.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 255 entries, 0 to 254
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Formulation    255 non-null    object
 1   Batch Number   254 non-null    object
dtypes: object(2)
memory usage: 4.1+ KB

In [109]:
outer_batch[outer_batch.isna().any(axis=1)]

   Formulation Batch Number
42     10% PVA           NaN

In [110]:
outer_batch =  outer_batch.dropna()
outer_batch.info()

<class 'pandas.core.frame.DataFrame'>
Index: 254 entries, 0 to 254
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Formulation    254 non-null    object
 1   Batch Number   254 non-null    object
dtypes: object(2)
memory usage: 6.0+ KB

## 9. AXF MANUFACTORING

In [111]:
mix.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 628 entries, 0 to 627
Data columns (total 32 columns):
 #   Column                                               Non-Null Count  Dtype
---  ------                                               --------------  -----
 0   AXF Number                                           628 non-null    object
 1   Date of experiment                                   628 non-null    datetime64[ns]
 2   Aims & Hypothesis                                    627 non-null    object
 3   Core used                                            628 non-null    object
 4   Core Formulation                                     628 non-null    object
 5   Core Viscosity (cP)                                  628 non-null    int64
 6   Amount of Core Used (g)                              625 non-null    float64
 7   UV used                                              628 non-null    object
 8   UV formulation                                       628 non-null    object
 9   UV viscosity (cP)                                    626 non-null    float64
 10  Amount of UV Used (g)                                625 non-null    float64
 11  Emulsion viscosity (cP)                              593 non-null    float64
 12  Emulsion Gear Pump used                              627 non-null    object
 13  Single Emulsion (SE) Number                          546 non-null    object
 14  Vessel Used                                          628 non-null    object
 15  Impellor Used                                        626 non-null    object
 16  Mass of emulsion used / g                            527 non-null    float64
 17  Impellor Speed (rpm)                                 626 non-null    float64
 18  Core Loading (%)                                     625 non-null    float64
 19  Outer used                                           625 non-null    object
 20  Outer viscosity (cP)                                 617 non-null    float64
 21  Outer Gear Pump Used                                 627 non-null    object
 22  Dispersed Flow Rate (mL/min)                         625 non-null    float64
 23  Continuous Flow Rate (mL/min)                        625 non-null    float64
 24  Flow Rate Ratio                                      625 non-null    float64
 25  Cure Rig Used                                        612 non-null    object
 26  Membrane Used (µm)                                   627 non-null    float64
 27  Insert used (mm)                                     626 non-null    float64
 28  Length of curing tubing (m)                          599 non-null    float64
 29  Temperature of Outer Phase at end of experiment / C  201 non-null    object
 30  UV Power (J s-1)                                     571 non-null    float64
 31  Curing Energy (kJ g-1)                               568 non-null    float64
dtypes: datetime64[ns](1), float64(16), int64(1), object(14)
memory usage: 157.1+ KB

There are many instances of incomplete documentation occurring simultaneously. Experiments with incomplete documentation in any category will be discarded due to a lack of information for analysis.

In [112]:
mix = mix.dropna()
mix.info()

<class 'pandas.core.frame.DataFrame'>
Index: 161 entries, 115 to 500
Data columns (total 32 columns):
 #   Column                                               Non-Null Count  Dtype
---  ------                                               --------------  -----
 0   AXF Number                                           161 non-null    object
 1   Date of experiment                                   161 non-null    datetime64[ns]
 2   Aims & Hypothesis                                    161 non-null    object
 3   Core used                                            161 non-null    object
 4   Core Formulation                                     161 non-null    object
 5   Core Viscosity (cP)                                  161 non-null    int64
 6   Amount of Core Used (g)                              161 non-null    float64
 7   UV used                                              161 non-null    object
 8   UV formulation                                       161 non-null    object
 9   UV viscosity (cP)                                    161 non-null    float64
 10  Amount of UV Used (g)                                161 non-null    float64
 11  Emulsion viscosity (cP)                              161 non-null    float64
 12  Emulsion Gear Pump used                              161 non-null    object
 13  Single Emulsion (SE) Number                          161 non-null    object
 14  Vessel Used                                          161 non-null    object
 15  Impellor Used                                        161 non-null    object
 16  Mass of emulsion used / g                            161 non-null    float64
 17  Impellor Speed (rpm)                                 161 non-null    float64
 18  Core Loading (%)                                     161 non-null    float64
 19  Outer used                                           161 non-null    object
 20  Outer viscosity (cP)                                 161 non-null    float64
 21  Outer Gear Pump Used                                 161 non-null    object
 22  Dispersed Flow Rate (mL/min)                         161 non-null    float64
 23  Continuous Flow Rate (mL/min)                        161 non-null    float64
 24  Flow Rate Ratio                                      161 non-null    float64
 25  Cure Rig Used                                        161 non-null    object
 26  Membrane Used (µm)                                   161 non-null    float64
 27  Insert used (mm)                                     161 non-null    float64
 28  Length of curing tubing (m)                          161 non-null    float64
 29  Temperature of Outer Phase at end of experiment / C  161 non-null    object
 30  UV Power (J s-1)                                     161 non-null    float64
 31  Curing Energy (kJ g-1)                               161 non-null    float64
dtypes: datetime64[ns](1), float64(16), int64(1), object(14)
memory usage: 41.5+ KB

In [113]:
mix.columns

Index(['AXF Number', 'Date of experiment', 'Aims & Hypothesis', 'Core used',
       'Core Formulation', 'Core Viscosity (cP)', 'Amount of Core Used (g)',
       'UV used', 'UV formulation', 'UV viscosity (cP)',
       'Amount of UV Used (g)', 'Emulsion viscosity (cP)',
       'Emulsion Gear Pump used', 'Single Emulsion (SE) Number', 'Vessel Used',
       'Impellor Used', 'Mass of emulsion used / g', 'Impellor Speed (rpm)',
       'Core Loading (%)', 'Outer used', 'Outer viscosity (cP)',
       'Outer Gear Pump Used', 'Dispersed Flow Rate (mL/min)',
       'Continuous Flow Rate (mL/min)', 'Flow Rate Ratio', 'Cure Rig Used',
       'Membrane Used (µm)', 'Insert used (mm)', 'Length of curing tubing (m)',
       'Temperature of Outer Phase at end of experiment / C',
       'UV Power (J s-1)', 'Curing Energy (kJ g-1)'],
      dtype='object')

In [114]:
for col in mix.columns:
    if col in ['AXF Number', 'Date of experiment', 'Aims & Hypothesis']:
        continue
    try:
        mix[col] = mix[col].astype('float64')
    except:
        pass

mix.dtypes.to_frame(name='dtype')

                                                             dtype
AXF Number                                                  object
Date of experiment                                  datetime64[ns]
Aims & Hypothesis                                           object
Core used                                                   object
Core Formulation                                            object
Core Viscosity (cP)                                        float64
Amount of Core Used (g)                                    float64
UV used                                                     object
UV formulation                                              object
UV viscosity (cP)                                          float64
Amount of UV Used (g)                                      float64
Emulsion viscosity (cP)                                    float64
Emulsion Gear Pump used                                     object
Single Emulsion (SE) Number                                 object
Vessel Used                                                 object
Impellor Used                                               object
Mass of emulsion used / g                                  float64
Impellor Speed (rpm)                                       float64
Core Loading (%)                                           float64
Outer used                                                  object
Outer viscosity (cP)                                       float64
Outer Gear Pump Used                                        object
Dispersed Flow Rate (mL/min)                               float64
Continuous Flow Rate (mL/min)                              float64
Flow Rate Ratio                                            float64
Cure Rig Used                                               object
Membrane Used (µm)                                         float64
Insert used (mm)                                           float64
Length of curing tubing (m)                                float64
Temperature of Outer Phase at end of experiment...          object
UV Power (J s-1)                                           float64
Curing Energy (kJ g-1)                                     float64

There were no unusual signs.

## 10. DURABILITY

In [115]:
result.info()
result

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 391 entries, 0 to 390
Data columns (total 6 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Batch number                            391 non-null    object
 1   UV formulation                          391 non-null    object
 2   Core formulation                        391 non-null    object
 3   % dry after 24h in humidity             391 non-null    int64
 4   % dry after 2 days in humidity chamber  391 non-null    int64
 5   QC Pass/Fail?                           391 non-null    object
dtypes: int64(2), object(4)
memory usage: 18.5+ KB

,Batch number,UV formulation,Core formulation,% dry after 24h in humidity,% dry after 2 days in humidity chamber,QC Pass/Fail?
0,AXF0045 (large),AUF76,RAD-C-0001,8,10,Pass
1,AXF0045 - 7 days,AUF76,RAD-C-0001,10,12,Pass
2,AXF0046,AUF76,RAD-C-0012,20,30,Fail
3,AXF0048,AUF91,RAD-C-0001,15,25,Pass
4,AXF0049,AUF90,RAD-C-0001,70,100,Fail
...,...,...,...,...,...,...
386,AXF0614,AUF285,RAD-C-0001,20,25,Pass
387,AXF0615,AUF285,RAD-C-0001,15,20,Pass
388,AXF0615,AUF285,RAD-C-0001,15,10,Pass
389,AXF0615,AUF285,RAD-C-0001,20,15,Pass
390,AXF0616,AUF285,RAD-C-0001,20,25,Pass

There were no unusual signs.

## EXPORT DATAFRAMES

In [ ]:
#uv.to_csv('../data/processed/uv_cleaned.csv', index = False)
#core.to_csv('../data/processed/core_cleaned.csv', index = False)
#outer.to_csv('../data/processed/outer_cleaned.csv', index = False)

#uv_batch.to_csv('../data/processed/uv_batch_cleaned.csv', index = False)
#core_batch.to_csv('../data/processed/core_batch_cleaned.csv', index = False)
#outer_batch.to_csv('../data/processed/outer_batch_cleaned.csv', index = False)

#mix.to_csv('../data/processed/mix_cleaned.csv', index = False)

#result.to_csv('../data/processed/result_cleaned.csv', index = False)