## 1. IMPORT NEEDED LIBRARY

In [34]:
import pandas as pd

## 2. READ FILES

In [35]:
uv_c = pd.read_csv('../data/processed/uv_cleaned.csv')
core_c = pd.read_csv('../data/processed/core_cleaned.csv')
outer_c = pd.read_csv('../data/processed/outer_cleaned.csv')

uv_b_c = pd.read_csv('../data/processed/uv_batch_cleaned.csv')
core_b_c = pd.read_csv('../data/processed/core_batch_cleaned.csv')
outer_b_c = pd.read_csv('../data/processed/outer_batch_cleaned.csv')

mix_c = pd.read_csv('../data/processed/mix_cleaned.csv')

result_c = pd.read_csv('../data/processed/result_cleaned.csv')

## 3. MERGE MIX WITH RESULT

In [36]:
result_c.head(5)

,Batch number,UV formulation,Core formulation,% dry after 24h in humidity,% dry after 2 days in humidity chamber,QC Pass/Fail?
0,AXF0045 (large),AUF76,RAD-C-0001,8,10,Pass
1,AXF0045 - 7 days,AUF76,RAD-C-0001,10,12,Pass
2,AXF0046,AUF76,RAD-C-0012,20,30,Fail
3,AXF0048,AUF91,RAD-C-0001,15,25,Pass
4,AXF0049,AUF90,RAD-C-0001,70,100,Fail

In [37]:
mix_c.head(5)

,AXF Number,Date of experiment,Aims & Hypothesis,Core used,Core Formulation,Core Viscosity (cP),Amount of Core Used (g),UV used,UV formulation,UV viscosity (cP),...,Dispersed Flow Rate (mL/min),Continuous Flow Rate (mL/min),Flow Rate Ratio,Cure Rig Used,Membrane Used (µm),Insert used (mm),Length of curing tubing (m),Temperature of Outer Phase at end of experiment / C,UV Power (J s-1),Curing Energy (kJ g-1)
0,AXF0119,2024-12-17,AUF76 w/OG core,BNC00041,RAD-C-0001,7356.0,1500.0,BNU00059,AUF076,254.4,...,20.0,100.0,5.00,Cure Rig 1.0,20.0,9.0,50.0,34.9,708.0,2.5488
1,AXF0120,2024-12-17,AUF76 w/OG core 440W cure,BNC00041,RAD-C-0001,7356.0,1500.0,BNU00059,AUF076,254.4,...,20.0,100.0,5.00,Cure Rig 1.0,20.0,9.0,50.0,32.1,440.0,1.5840
2,AXF0128,2025-01-21,AUF110 w/OG core old rig,BNC00044,RAD-C-0001,9036.0,1500.0,BNU00068,AUF110,375.6,...,30.0,150.0,5.00,Cure Rig 1.0,20.0,9.0,50.0,28.5,708.0,1.6992
3,AXF0129,2025-01-21,AUF110 w/OG core old rig 488W,BNC00044,RAD-C-0001,9036.0,1500.0,BNU00068,AUF110,375.6,...,30.0,150.0,5.00,Cure Rig 1.0,20.0,9.0,50.0,28.7,488.0,1.1712
4,AXF0130,2025-01-21,AUF110 w/OG core old rig 488W diff. flow rate ...,BNC00044,RAD-C-0001,9036.0,1500.0,BNU00068,AUF110,375.6,...,40.0,150.0,3.75,Cure Rig 1.0,20.0,9.0,50.0,29.5,488.0,0.9272

These two data frames will be merged via 'AXF Number', so verification needs to be performed.

In [38]:
print(result_c['Batch number'].unique())

['AXF0045 (large)' 'AXF0045 - 7 days' 'AXF0046' 'AXF0048 ' 'AXF0049 '
 'AXF0050 ' 'AXF0051 ' 'AXF0052' 'AXF0053' 'AXF0054 ' 'AXF0055' 'AXF0056'
 'AXF0057 ' 'AXF0057' 'AXF0058 ' 'AXF0059' 'AXF0060' 'AXF0061' 'AXF0062'
 'AXF0063' 'AXF0064' 'AXF0065' 'AXF0066' 'AXF0067' 'AXF0068' 'AXF0069'
 'AXF0070' 'AXF0071' 'AXF0072' 'AXF0072 ' 'AXF0073' 'AXF0074' 'AXF0075'
 'AXF0076' 'AXF0077' 'AXF0078' 'AXF0079' 'AXF0080' 'AXF0081' 'AXF0082'
 'AXF0083' 'AXF0084' 'AXF0086' 'AXF0087' 'AXF0087 ' 'AXF0089' 'AXF0089 '
 'AXF0090 ' 'AXF0091' 'AXF0092 ' 'AXF0093' 'AXF0094' 'AXF0095' 'AXF0096'
 'AXF0097' 'AXF0098' 'AXF0099' 'AXF0100' 'AXF0101' 'AXF0102' 'AXF0103'
 'AXF0103 ' 'AXF0105' 'AXF0106' 'AXF0108' 'AXF0109' 'AXF0111' 'AXF0112'
 'AXF0113' 'AXF0114' 'AXF0115' 'AXF0116' 'AXF0117' 'AXF0118' 'AXF0119'
 'AXF0123' 'AXF0128' 'AXF0129' 'AXF0130' 'AXF0131 ' 'AXF0132' 'AXF0133'
 'AXF0133 ' 'AXF0134' 'AXF0134 ' 'AXF0136' 'AXF0136 ' 'AXF0137' 'AXF0137 '
 'AXF0138' 'AXF0138 ' 'AXF0139' 'AXF0139 ' 'AXF0140' 'AXF0140 ' 'AXF0141 '
 'AXF0142' 'AXF0142 ' 'AXF0143' 'AXF0143 ' 'AXF0144' 'AXF0144 ' 'AXF0145'
 'AXF0145 ' 'AXF0146' 'AXF0146 ' 'AXF0147' 'AXF0147 ' 'AXF0148' 'AXF0148 '
 'AXF0149' 'AXF0149 ' 'AXF0150' 'AXF0150 ' 'AXF0151' 'AXF0151 ' 'AXF0153 '
 'AXF0154 ' 'AXF0155 ' 'AXF0156 ' 'AXF0157 ' 'AXF0158 ' 'AXF0159 '
 'AXF0160 ' 'AXF0161 ' 'AXF0162 ' 'AXF0163 ' 'AXF0166' 'AXF0167 '
 'AXF0168 ' 'AXF0169' 'AXF0170' 'AXF0171' 'AXF0172' 'AXF0173' 'AXF0175 '
 'AXF0176' 'AXF0177' 'AXF0178' 'AXF0179' 'AXF0180' 'AXF0181' 'AXF0182'
 'AXF0183' 'AXF0185' 'AXF0186' 'AXF0187' 'AXF0188' 'AXF0194' 'AXF0197'
 'AXF0198' 'AXF0199' 'AXF0200' 'AXF0201' 'AXF0203' 'AXF0204' 'AXF0205'
 'AXF0208' 'AXF0209' 'AXF0210' 'AXF0211' 'AXF0212' 'AXF0213' 'AXF0214'
 'AXF0215' 'AXF0216' 'AXF0217' 'AXF0218' 'AXF0221' 'AXF0222' 'AXF0223'
 'AXF0225' 'AXF0227' 'AXF0228' 'AXF0229' 'AXF0230' 'AXF0231' 'AXF0232'
 'AXF0233' 'AXF0234' 'AXF0236' 'AXF0237' 'AXF0238' 'AXF0239' 'AXF0240'
 'AXF0241' 'AXF0242' 'AXF0243' 'AXF0245' 'AXF0246' 'AXF0248' 'AXF0250'
 'AXF0251' 'AXF0254' 'AXF0255' 'AXF0258' 'AXF0267' 'AXF0270' 'AXF0271'
 'AXF0273' 'AXF0274' 'AXF0275' 'AXF0276' 'AXF0279' 'AXF0280' 'AXF0281'
 'AXF0282' 'AXF0283' 'AXF0284' 'AXF0289' 'AXF0297' 'AXF0306' 'AXF0307'
 'AXF0308' 'AXF0309' 'AXF0310' 'AXF0311' 'AXF0312' 'AXF0313' 'AXF0314'
 'AXF0315' 'AXF0316' 'AXF0317' 'AXF0318' 'AXF0322' 'AXF0323' 'AXF0332'
 'AXF0333' 'AXF0335' 'AXF0336' 'AXF0337' 'AXF0352' 'AXF0374' 'AXF0376'
 'AXF0377' 'AXF0378' 'AXF0380' 'AXF0381' 'AXF0382' 'AXF0391' 'AXF0392'
 'AXF0393' 'AXF0394' 'AXF0400' 'AXF0401' 'AXF0402' 'AXF0403' 'AXF0412'
 'AXF0413' 'AXF0414' 'AXF0415' 'AXF0416' 'AXF0417' 'AXF0419' 'AXF0420'
 'AXF0421' 'AXF0422' 'AXF0431' 'AXF0432' 'AXF0433' 'AXF0435' 'AXF0436'
 'AXF0437' 'AXF0438' 'AXF0439' 'AXF0440' 'AXF0441' 'AXF0442' 'AXF0443'
 'AXF0444' 'AXF0445' 'AXF0446' 'AXF0447' 'AXF0448' 'AXF0449' 'AXF0450'
 'AXF0451' 'AXF0452' 'AXF0453' 'AXF0454' 'AXF0455' 'AXF0456' 'AXF0457'
 'AXF0458' 'AXF0459' 'AXF0460' 'AXF0461' 'AXF0462' 'AXF0463' 'AXF0464'
 'AXF0465' 'AXF0466' 'AXF0468' 'AXF0469' 'AXF0470' 'AXF0486' 'AXF0487'
 'AXF0488' 'AXF0490 ' 'AXF0491 ' 'AXF0492 ' 'AXF0493 ' 'AXF0494 '
 'AXF0496 ' 'AXF0497 ' 'AXF0498 ' 'AXF0499 ' 'AXF0499' 'AXF0500 '
 'AXF0500' 'AXF0501 ' 'AXF0501' 'AXF0505 ' 'AXF0506 ' 'AXF0507 '
 'AXF0526 ' 'AXF0527 ' 'AXF0528 ' 'AXF0535 ' 'AXF0542 ' 'AXF0542.1'
 'AXF0543 ' 'AXF0544 ' 'AXF0545 ' 'AXF0545.1 ' 'AXF0546 ' 'AXF0581'
 'AXF0582' 'AXF0583' 'AXF0584' 'AXF0585' 'AXF0590' 'AXF0591' 'AXF0592'
 'AXF0593' 'AXF0594' 'AXF0595' 'AXF0597' 'AXF0598' 'AXF0599' 'AXF0600'
 'AXF0601' 'AXF0602' 'AXF0604' 'AXF0605' 'AXF0606' 'AXF0607' 'AXF0608'
 'AXF0609' 'AXF0610' 'AXF0611' 'AXF0612' 'AXF0613' 'AXF0614' 'AXF0615'
 'AXF0616']

In [39]:
print(mix_c['AXF Number'].unique())

['AXF0119' 'AXF0120' 'AXF0128' 'AXF0129' 'AXF0130' 'AXF0131' 'AXF0132'
 'AXF0133' 'AXF0134' 'AXF0135' 'AXF0136' 'AXF0137' 'AXF0138' 'AXF0139'
 'AXF0140' 'AXF0141' 'AXF0142' 'AXF0143' 'AXF0144' 'AXF0145' 'AXF0146'
 'AXF0147' 'AXF0148' 'AXF0149' 'AXF0150' 'AXF0151' 'AXF0152' 'AXF0153'
 'AXF0155' 'AXF0156' 'AXF0157' 'AXF0158' 'AXF0159' 'AXF0160' 'AXF0161'
 'AXF0162' 'AXF0163' 'AXF0166' 'AXF0167' 'AXF0168' 'AXF0169' 'AXF0170'
 'AXF0171' 'AXF0172' 'AXF0173' 'AXF0175' 'AXF0176' 'AXF0177' 'AXF0178'
 'AXF0179' 'AXF0180' 'AXF0181' 'AXF0182' 'AXF0183' 'AXF0186' 'AXF0187'
 'AXF0188' 'AXF0190' 'AXF0191' 'AXF0192' 'AXF0194' 'AXF0196' 'AXF0199'
 'AXF0200' 'AXF0201' 'AXF0203' 'AXF0204' 'AXF0205' 'AXF0206' 'AXF0207'
 'AXF0208' 'AXF0209' 'AXF0211' 'AXF0213' 'AXF0214' 'AXF0215' 'AXF0216'
 'AXF0217' 'AXF0218' 'AXF0219' 'AXF0221' 'AXF0222' 'AXF0223' 'AXF0225'
 'AXF0227' 'AXF0229' 'AXF0230' 'AXF0231' 'AXF0232' 'AXF0233' 'AXF0250'
 'AXF0262' 'AXF0264' 'AXF0267' 'AXF0268' 'AXF0269' 'AXF0270' 'AXF0272'
 'AXF0273' 'AXF0274' 'AXF0277' 'AXF0278' 'AXF0279' 'AXF0280' 'AXF0282'
 'AXF0283' 'AXF0285' 'AXF0286' 'AXF0287' 'AXF0288' 'AXF0289' 'AXF0352'
 'AXF0355' 'AXF0362' 'AXF0370' 'AXF0371' 'AXF0373' 'AXF0374' 'AXF0375'
 'AXF0376' 'AXF0379' 'AXF0380' 'AXF0381' 'AXF0382' 'AXF0383' 'AXF0384'
 'AXF0385' 'AXF0386' 'AXF0387' 'AXF0388' 'AXF0389' 'AXF0390' 'AXF0391'
 'AXF0392' 'AXF0394' 'AXF0395' 'AXF0396' 'AXF0397' 'AXF0398' 'AXF0399'
 'AXF0424' 'AXF0439' 'AXF0485' 'AXF0486' 'AXF0487' 'AXF0488' 'AXF0490'
 'AXF0491' 'AXF0492' 'AXF0493' 'AXF0494' 'AXF0495' 'AXF0496' 'AXF0497'
 'AXF0498' 'AXF0499' 'AXF0500' 'AXF0501' 'AXF0502' 'AXF0503' 'AXF0504']

There are a few experiments in 'result_cleaned' file with special markings ('AXF0045 (large)' and 'AXF0045 - 7 days') and some experiments with typographical errors where an extra space is present in the name. <br>
<br>
These experiments will be processed to reduce the number of unique values. <br>
<br>
File 'mix_cleaned' file shows no unusual signs.

In [40]:
result_c['Batch number'] = result_c['Batch number'].str.strip()
print(result_c['Batch number'].unique())

['AXF0045 (large)' 'AXF0045 - 7 days' 'AXF0046' 'AXF0048' 'AXF0049'
 'AXF0050' 'AXF0051' 'AXF0052' 'AXF0053' 'AXF0054' 'AXF0055' 'AXF0056'
 'AXF0057' 'AXF0058' 'AXF0059' 'AXF0060' 'AXF0061' 'AXF0062' 'AXF0063'
 'AXF0064' 'AXF0065' 'AXF0066' 'AXF0067' 'AXF0068' 'AXF0069' 'AXF0070'
 'AXF0071' 'AXF0072' 'AXF0073' 'AXF0074' 'AXF0075' 'AXF0076' 'AXF0077'
 'AXF0078' 'AXF0079' 'AXF0080' 'AXF0081' 'AXF0082' 'AXF0083' 'AXF0084'
 'AXF0086' 'AXF0087' 'AXF0089' 'AXF0090' 'AXF0091' 'AXF0092' 'AXF0093'
 'AXF0094' 'AXF0095' 'AXF0096' 'AXF0097' 'AXF0098' 'AXF0099' 'AXF0100'
 'AXF0101' 'AXF0102' 'AXF0103' 'AXF0105' 'AXF0106' 'AXF0108' 'AXF0109'
 'AXF0111' 'AXF0112' 'AXF0113' 'AXF0114' 'AXF0115' 'AXF0116' 'AXF0117'
 'AXF0118' 'AXF0119' 'AXF0123' 'AXF0128' 'AXF0129' 'AXF0130' 'AXF0131'
 'AXF0132' 'AXF0133' 'AXF0134' 'AXF0136' 'AXF0137' 'AXF0138' 'AXF0139'
 'AXF0140' 'AXF0141' 'AXF0142' 'AXF0143' 'AXF0144' 'AXF0145' 'AXF0146'
 'AXF0147' 'AXF0148' 'AXF0149' 'AXF0150' 'AXF0151' 'AXF0153' 'AXF0154'
 'AXF0155' 'AXF0156' 'AXF0157' 'AXF0158' 'AXF0159' 'AXF0160' 'AXF0161'
 'AXF0162' 'AXF0163' 'AXF0166' 'AXF0167' 'AXF0168' 'AXF0169' 'AXF0170'
 'AXF0171' 'AXF0172' 'AXF0173' 'AXF0175' 'AXF0176' 'AXF0177' 'AXF0178'
 'AXF0179' 'AXF0180' 'AXF0181' 'AXF0182' 'AXF0183' 'AXF0185' 'AXF0186'
 'AXF0187' 'AXF0188' 'AXF0194' 'AXF0197' 'AXF0198' 'AXF0199' 'AXF0200'
 'AXF0201' 'AXF0203' 'AXF0204' 'AXF0205' 'AXF0208' 'AXF0209' 'AXF0210'
 'AXF0211' 'AXF0212' 'AXF0213' 'AXF0214' 'AXF0215' 'AXF0216' 'AXF0217'
 'AXF0218' 'AXF0221' 'AXF0222' 'AXF0223' 'AXF0225' 'AXF0227' 'AXF0228'
 'AXF0229' 'AXF0230' 'AXF0231' 'AXF0232' 'AXF0233' 'AXF0234' 'AXF0236'
 'AXF0237' 'AXF0238' 'AXF0239' 'AXF0240' 'AXF0241' 'AXF0242' 'AXF0243'
 'AXF0245' 'AXF0246' 'AXF0248' 'AXF0250' 'AXF0251' 'AXF0254' 'AXF0255'
 'AXF0258' 'AXF0267' 'AXF0270' 'AXF0271' 'AXF0273' 'AXF0274' 'AXF0275'
 'AXF0276' 'AXF0279' 'AXF0280' 'AXF0281' 'AXF0282' 'AXF0283' 'AXF0284'
 'AXF0289' 'AXF0297' 'AXF0306' 'AXF0307' 'AXF0308' 'AXF0309' 'AXF0310'
 'AXF0311' 'AXF0312' 'AXF0313' 'AXF0314' 'AXF0315' 'AXF0316' 'AXF0317'
 'AXF0318' 'AXF0322' 'AXF0323' 'AXF0332' 'AXF0333' 'AXF0335' 'AXF0336'
 'AXF0337' 'AXF0352' 'AXF0374' 'AXF0376' 'AXF0377' 'AXF0378' 'AXF0380'
 'AXF0381' 'AXF0382' 'AXF0391' 'AXF0392' 'AXF0393' 'AXF0394' 'AXF0400'
 'AXF0401' 'AXF0402' 'AXF0403' 'AXF0412' 'AXF0413' 'AXF0414' 'AXF0415'
 'AXF0416' 'AXF0417' 'AXF0419' 'AXF0420' 'AXF0421' 'AXF0422' 'AXF0431'
 'AXF0432' 'AXF0433' 'AXF0435' 'AXF0436' 'AXF0437' 'AXF0438' 'AXF0439'
 'AXF0440' 'AXF0441' 'AXF0442' 'AXF0443' 'AXF0444' 'AXF0445' 'AXF0446'
 'AXF0447' 'AXF0448' 'AXF0449' 'AXF0450' 'AXF0451' 'AXF0452' 'AXF0453'
 'AXF0454' 'AXF0455' 'AXF0456' 'AXF0457' 'AXF0458' 'AXF0459' 'AXF0460'
 'AXF0461' 'AXF0462' 'AXF0463' 'AXF0464' 'AXF0465' 'AXF0466' 'AXF0468'
 'AXF0469' 'AXF0470' 'AXF0486' 'AXF0487' 'AXF0488' 'AXF0490' 'AXF0491'
 'AXF0492' 'AXF0493' 'AXF0494' 'AXF0496' 'AXF0497' 'AXF0498' 'AXF0499'
 'AXF0500' 'AXF0501' 'AXF0505' 'AXF0506' 'AXF0507' 'AXF0526' 'AXF0527'
 'AXF0528' 'AXF0535' 'AXF0542' 'AXF0542.1' 'AXF0543' 'AXF0544' 'AXF0545'
 'AXF0545.1' 'AXF0546' 'AXF0581' 'AXF0582' 'AXF0583' 'AXF0584' 'AXF0585'
 'AXF0590' 'AXF0591' 'AXF0592' 'AXF0593' 'AXF0594' 'AXF0595' 'AXF0597'
 'AXF0598' 'AXF0599' 'AXF0600' 'AXF0601' 'AXF0602' 'AXF0604' 'AXF0605'
 'AXF0606' 'AXF0607' 'AXF0608' 'AXF0609' 'AXF0610' 'AXF0611' 'AXF0612'
 'AXF0613' 'AXF0614' 'AXF0615' 'AXF0616']

It can be seen that experiment 'AXF0045' has records in two different special cases.

In [41]:
result_c[result_c['Batch number'].str.contains('AXF0045')]

,Batch number,UV formulation,Core formulation,% dry after 24h in humidity,% dry after 2 days in humidity chamber,QC Pass/Fail?
0,AXF0045 (large),AUF76,RAD-C-0001,8,10,Pass
1,AXF0045 - 7 days,AUF76,RAD-C-0001,10,12,Pass

The head's experiments were always quality-checked at 24 hours, 48 ​​hours, and 7 days. <br>
However, the dataset consistently presented information on quality-check results within 24 hours and 48 hours. <br>
Therefore, the experiment line 'AXF0045 - 7 days' was removed.<br>
<br>
The experiment name 'AXF0045 (large)' will be changed to 'AXF0045'

In [42]:
result_c = result_c.drop(result_c[(result_c['Batch number'] == 'AXF0045 - 7 days')].index)

result_c.loc[0, 'Batch number'] = 'AXF0045'

To join two data frames, we need to rename the 'Batch number' column in 'result_c' to 'AXF Number' first.

In [43]:
result_c = result_c.rename(columns={'Batch number': 'AXF Number'})
merge_1 = mix_c.merge(result_c,how='left', on=['AXF Number'])
merge_1.info()
print('-'*50)
merge_1.head(5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 196 entries, 0 to 195
Data columns (total 37 columns):
 #   Column                                               Non-Null Count  Dtype
---  ------                                               --------------  -----
 0   AXF Number                                           196 non-null    object
 1   Date of experiment                                   196 non-null    object
 2   Aims & Hypothesis                                    196 non-null    object
 3   Core used                                            196 non-null    object
 4   Core Formulation                                     196 non-null    object
 5   Core Viscosity (cP)                                  196 non-null    float64
 6   Amount of Core Used (g)                              196 non-null    float64
 7   UV used                                              196 non-null    object
 8   UV formulation_x                                     196 non-null    object
 9   UV viscosity (cP)                                    196 non-null    float64
 10  Amount of UV Used (g)                                196 non-null    float64
 11  Emulsion viscosity (cP)                              196 non-null    float64
 12  Emulsion Gear Pump used                              196 non-null    object
 13  Single Emulsion (SE) Number                          196 non-null    object
 14  Vessel Used                                          196 non-null    object
 15  Impellor Used                                        196 non-null    object
 16  Mass of emulsion used / g                            196 non-null    float64
 17  Impellor Speed (rpm)                                 196 non-null    float64
 18  Core Loading (%)                                     196 non-null    float64
 19  Outer used                                           196 non-null    object
 20  Outer viscosity (cP)                                 196 non-null    float64
 21  Outer Gear Pump Used                                 196 non-null    object
 22  Dispersed Flow Rate (mL/min)                         196 non-null    float64
 23  Continuous Flow Rate (mL/min)                        196 non-null    float64
 24  Flow Rate Ratio                                      196 non-null    float64
 25  Cure Rig Used                                        196 non-null    object
 26  Membrane Used (µm)                                   196 non-null    float64
 27  Insert used (mm)                                     196 non-null    float64
 28  Length of curing tubing (m)                          196 non-null    float64
 29  Temperature of Outer Phase at end of experiment / C  196 non-null    object
 30  UV Power (J s-1)                                     196 non-null    float64
 31  Curing Energy (kJ g-1)                               196 non-null    float64
 32  UV formulation_y                                     149 non-null    object
 33  Core formulation                                     149 non-null    object
 34  % dry after 24h in humidity                          149 non-null    float64
 35  % dry after 2 days in humidity chamber               149 non-null    float64
 36  QC Pass/Fail?                                        149 non-null    object
dtypes: float64(19), object(18)
memory usage: 56.8+ KB
--------------------------------------------------

,AXF Number,Date of experiment,Aims & Hypothesis,Core used,Core Formulation,Core Viscosity (cP),Amount of Core Used (g),UV used,UV formulation_x,UV viscosity (cP),...,Insert used (mm),Length of curing tubing (m),Temperature of Outer Phase at end of experiment / C,UV Power (J s-1),Curing Energy (kJ g-1),UV formulation_y,Core formulation,% dry after 24h in humidity,% dry after 2 days in humidity chamber,QC Pass/Fail?
0,AXF0119,2024-12-17,AUF76 w/OG core,BNC00041,RAD-C-0001,7356.0,1500.0,BNU00059,AUF076,254.4,...,9.0,50.0,34.9,708.0,2.5488,AUF76,RAD-C-0001,15.0,15.0,Pass
1,AXF0120,2024-12-17,AUF76 w/OG core 440W cure,BNC00041,RAD-C-0001,7356.0,1500.0,BNU00059,AUF076,254.4,...,9.0,50.0,32.1,440.0,1.5840,NaN,NaN,NaN,NaN,NaN
2,AXF0128,2025-01-21,AUF110 w/OG core old rig,BNC00044,RAD-C-0001,9036.0,1500.0,BNU00068,AUF110,375.6,...,9.0,50.0,28.5,708.0,1.6992,AUF110,RAD-C-0001,50.0,60.0,Fail
3,AXF0129,2025-01-21,AUF110 w/OG core old rig 488W,BNC00044,RAD-C-0001,9036.0,1500.0,BNU00068,AUF110,375.6,...,9.0,50.0,28.7,488.0,1.1712,AUF110,RAD-C-0001,30.0,70.0,Fail
4,AXF0130,2025-01-21,AUF110 w/OG core old rig 488W diff. flow rate ...,BNC00044,RAD-C-0001,9036.0,1500.0,BNU00068,AUF110,375.6,...,9.0,50.0,29.5,488.0,0.9272,AUF110,RAD-C-0001,2.0,5.0,Pass

In [44]:
merge_1.columns

Index(['AXF Number', 'Date of experiment', 'Aims & Hypothesis', 'Core used',
       'Core Formulation', 'Core Viscosity (cP)', 'Amount of Core Used (g)',
       'UV used', 'UV formulation_x', 'UV viscosity (cP)',
       'Amount of UV Used (g)', 'Emulsion viscosity (cP)',
       'Emulsion Gear Pump used', 'Single Emulsion (SE) Number', 'Vessel Used',
       'Impellor Used', 'Mass of emulsion used / g', 'Impellor Speed (rpm)',
       'Core Loading (%)', 'Outer used', 'Outer viscosity (cP)',
       'Outer Gear Pump Used', 'Dispersed Flow Rate (mL/min)',
       'Continuous Flow Rate (mL/min)', 'Flow Rate Ratio', 'Cure Rig Used',
       'Membrane Used (µm)', 'Insert used (mm)', 'Length of curing tubing (m)',
       'Temperature of Outer Phase at end of experiment / C',
       'UV Power (J s-1)', 'Curing Energy (kJ g-1)', 'UV formulation_y',
       'Core formulation ', '% dry after 24h in humidity',
       '% dry after 2 days in humidity chamber', 'QC Pass/Fail?'],
      dtype='object')

'Date of experiment', 'Aims & Hypothesis' will be droped because they are not helpful in the analysis. <br>
'UV formulation_y' and 'Core formulation' will be dropped because they conflict with columns that share the same name and data as other columns in the data frame.<br>
'QC Pass/Fail?' will be dropped because the data in this column is considered based on the old condition (rule 35,50,75).

In [45]:
merge_1 = merge_1.drop(columns=['Date of experiment', 
                                'Aims & Hypothesis',
                                'UV formulation_y',
                                'Core formulation ',
                                'QC Pass/Fail?'])
merge_1.rename(columns = {'UV formulation_x': 'UV formulation'}, inplace = True)
merge_1.info()
print('-'*50)
merge_1.head(5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 196 entries, 0 to 195
Data columns (total 32 columns):
 #   Column                                               Non-Null Count  Dtype
---  ------                                               --------------  -----
 0   AXF Number                                           196 non-null    object
 1   Core used                                            196 non-null    object
 2   Core Formulation                                     196 non-null    object
 3   Core Viscosity (cP)                                  196 non-null    float64
 4   Amount of Core Used (g)                              196 non-null    float64
 5   UV used                                              196 non-null    object
 6   UV formulation                                       196 non-null    object
 7   UV viscosity (cP)                                    196 non-null    float64
 8   Amount of UV Used (g)                                196 non-null    float64
 9   Emulsion viscosity (cP)                              196 non-null    float64
 10  Emulsion Gear Pump used                              196 non-null    object
 11  Single Emulsion (SE) Number                          196 non-null    object
 12  Vessel Used                                          196 non-null    object
 13  Impellor Used                                        196 non-null    object
 14  Mass of emulsion used / g                            196 non-null    float64
 15  Impellor Speed (rpm)                                 196 non-null    float64
 16  Core Loading (%)                                     196 non-null    float64
 17  Outer used                                           196 non-null    object
 18  Outer viscosity (cP)                                 196 non-null    float64
 19  Outer Gear Pump Used                                 196 non-null    object
 20  Dispersed Flow Rate (mL/min)                         196 non-null    float64
 21  Continuous Flow Rate (mL/min)                        196 non-null    float64
 22  Flow Rate Ratio                                      196 non-null    float64
 23  Cure Rig Used                                        196 non-null    object
 24  Membrane Used (µm)                                   196 non-null    float64
 25  Insert used (mm)                                     196 non-null    float64
 26  Length of curing tubing (m)                          196 non-null    float64
 27  Temperature of Outer Phase at end of experiment / C  196 non-null    object
 28  UV Power (J s-1)                                     196 non-null    float64
 29  Curing Energy (kJ g-1)                               196 non-null    float64
 30  % dry after 24h in humidity                          149 non-null    float64
 31  % dry after 2 days in humidity chamber               149 non-null    float64
dtypes: float64(19), object(13)
memory usage: 49.1+ KB
--------------------------------------------------

,AXF Number,Core used,Core Formulation,Core Viscosity (cP),Amount of Core Used (g),UV used,UV formulation,UV viscosity (cP),Amount of UV Used (g),Emulsion viscosity (cP),...,Flow Rate Ratio,Cure Rig Used,Membrane Used (µm),Insert used (mm),Length of curing tubing (m),Temperature of Outer Phase at end of experiment / C,UV Power (J s-1),Curing Energy (kJ g-1),% dry after 24h in humidity,% dry after 2 days in humidity chamber
0,AXF0119,BNC00041,RAD-C-0001,7356.0,1500.0,BNU00059,AUF076,254.4,3500.0,520.8,...,5.00,Cure Rig 1.0,20.0,9.0,50.0,34.9,708.0,2.5488,15.0,15.0
1,AXF0120,BNC00041,RAD-C-0001,7356.0,1500.0,BNU00059,AUF076,254.4,3500.0,520.8,...,5.00,Cure Rig 1.0,20.0,9.0,50.0,32.1,440.0,1.5840,NaN,NaN
2,AXF0128,BNC00044,RAD-C-0001,9036.0,1500.0,BNU00068,AUF110,375.6,3500.0,697.2,...,5.00,Cure Rig 1.0,20.0,9.0,50.0,28.5,708.0,1.6992,50.0,60.0
3,AXF0129,BNC00044,RAD-C-0001,9036.0,1500.0,BNU00068,AUF110,375.6,3500.0,697.2,...,5.00,Cure Rig 1.0,20.0,9.0,50.0,28.7,488.0,1.1712,30.0,70.0
4,AXF0130,BNC00044,RAD-C-0001,9036.0,1500.0,BNU00068,AUF110,375.6,3500.0,697.2,...,3.75,Cure Rig 1.0,20.0,9.0,50.0,29.5,488.0,0.9272,2.0,5.0

In [46]:
merge_1.isna().sum().to_frame()

                                                     0
AXF Number                                           0
Core used                                            0
Core Formulation                                     0
Core Viscosity (cP)                                  0
Amount of Core Used (g)                              0
UV used                                              0
UV formulation                                       0
UV viscosity (cP)                                    0
Amount of UV Used (g)                                0
Emulsion viscosity (cP)                              0
Emulsion Gear Pump used                              0
Single Emulsion (SE) Number                          0
Vessel Used                                          0
Impellor Used                                        0
Mass of emulsion used / g                            0
Impellor Speed (rpm)                                 0
Core Loading (%)                                     0
Outer used                                           0
Outer viscosity (cP)                                 0
Outer Gear Pump Used                                 0
Dispersed Flow Rate (mL/min)                         0
Continuous Flow Rate (mL/min)                        0
Flow Rate Ratio                                      0
Cure Rig Used                                        0
Membrane Used (µm)                                   0
Insert used (mm)                                     0
Length of curing tubing (m)                          0
Temperature of Outer Phase at end of experiment...   0
UV Power (J s-1)                                     0
Curing Energy (kJ g-1)                               0
% dry after 24h in humidity                         47
% dry after 2 days in humidity chamber              47

There are still 47 rows with missing data in '% dry after 24h in humidity' and '% dry after 2 days in humidity chamber'.

In [47]:
merge_1 = merge_1.dropna()
merge_1.isna().sum().to_frame()

                                                    0
AXF Number                                          0
Core used                                           0
Core Formulation                                    0
Core Viscosity (cP)                                 0
Amount of Core Used (g)                             0
UV used                                             0
UV formulation                                      0
UV viscosity (cP)                                   0
Amount of UV Used (g)                               0
Emulsion viscosity (cP)                             0
Emulsion Gear Pump used                             0
Single Emulsion (SE) Number                         0
Vessel Used                                         0
Impellor Used                                       0
Mass of emulsion used / g                           0
Impellor Speed (rpm)                                0
Core Loading (%)                                    0
Outer used                                          0
Outer viscosity (cP)                                0
Outer Gear Pump Used                                0
Dispersed Flow Rate (mL/min)                        0
Continuous Flow Rate (mL/min)                       0
Flow Rate Ratio                                     0
Cure Rig Used                                       0
Membrane Used (µm)                                  0
Insert used (mm)                                    0
Length of curing tubing (m)                         0
Temperature of Outer Phase at end of experiment...  0
UV Power (J s-1)                                    0
Curing Energy (kJ g-1)                              0
% dry after 24h in humidity                         0
% dry after 2 days in humidity chamber              0

In [48]:
merge_1.info()
print('-'*50)
merge_1.head(5)

<class 'pandas.core.frame.DataFrame'>
Index: 149 entries, 0 to 192
Data columns (total 32 columns):
 #   Column                                               Non-Null Count  Dtype
---  ------                                               --------------  -----
 0   AXF Number                                           149 non-null    object
 1   Core used                                            149 non-null    object
 2   Core Formulation                                     149 non-null    object
 3   Core Viscosity (cP)                                  149 non-null    float64
 4   Amount of Core Used (g)                              149 non-null    float64
 5   UV used                                              149 non-null    object
 6   UV formulation                                       149 non-null    object
 7   UV viscosity (cP)                                    149 non-null    float64
 8   Amount of UV Used (g)                                149 non-null    float64
 9   Emulsion viscosity (cP)                              149 non-null    float64
 10  Emulsion Gear Pump used                              149 non-null    object
 11  Single Emulsion (SE) Number                          149 non-null    object
 12  Vessel Used                                          149 non-null    object
 13  Impellor Used                                        149 non-null    object
 14  Mass of emulsion used / g                            149 non-null    float64
 15  Impellor Speed (rpm)                                 149 non-null    float64
 16  Core Loading (%)                                     149 non-null    float64
 17  Outer used                                           149 non-null    object
 18  Outer viscosity (cP)                                 149 non-null    float64
 19  Outer Gear Pump Used                                 149 non-null    object
 20  Dispersed Flow Rate (mL/min)                         149 non-null    float64
 21  Continuous Flow Rate (mL/min)                        149 non-null    float64
 22  Flow Rate Ratio                                      149 non-null    float64
 23  Cure Rig Used                                        149 non-null    object
 24  Membrane Used (µm)                                   149 non-null    float64
 25  Insert used (mm)                                     149 non-null    float64
 26  Length of curing tubing (m)                          149 non-null    float64
 27  Temperature of Outer Phase at end of experiment / C  149 non-null    object
 28  UV Power (J s-1)                                     149 non-null    float64
 29  Curing Energy (kJ g-1)                               149 non-null    float64
 30  % dry after 24h in humidity                          149 non-null    float64
 31  % dry after 2 days in humidity chamber               149 non-null    float64
dtypes: float64(19), object(13)
memory usage: 38.4+ KB
--------------------------------------------------

,AXF Number,Core used,Core Formulation,Core Viscosity (cP),Amount of Core Used (g),UV used,UV formulation,UV viscosity (cP),Amount of UV Used (g),Emulsion viscosity (cP),...,Flow Rate Ratio,Cure Rig Used,Membrane Used (µm),Insert used (mm),Length of curing tubing (m),Temperature of Outer Phase at end of experiment / C,UV Power (J s-1),Curing Energy (kJ g-1),% dry after 24h in humidity,% dry after 2 days in humidity chamber
0,AXF0119,BNC00041,RAD-C-0001,7356.0,1500.0,BNU00059,AUF076,254.4,3500.0,520.8,...,5.00,Cure Rig 1.0,20.0,9.0,50.0,34.9,708.0,2.5488,15.0,15.0
2,AXF0128,BNC00044,RAD-C-0001,9036.0,1500.0,BNU00068,AUF110,375.6,3500.0,697.2,...,5.00,Cure Rig 1.0,20.0,9.0,50.0,28.5,708.0,1.6992,50.0,60.0
3,AXF0129,BNC00044,RAD-C-0001,9036.0,1500.0,BNU00068,AUF110,375.6,3500.0,697.2,...,5.00,Cure Rig 1.0,20.0,9.0,50.0,28.7,488.0,1.1712,30.0,70.0
4,AXF0130,BNC00044,RAD-C-0001,9036.0,1500.0,BNU00068,AUF110,375.6,3500.0,697.2,...,3.75,Cure Rig 1.0,20.0,9.0,50.0,29.5,488.0,0.9272,2.0,5.0
5,AXF0130,BNC00044,RAD-C-0001,9036.0,1500.0,BNU00068,AUF110,375.6,3500.0,697.2,...,3.75,Cure Rig 1.0,20.0,9.0,50.0,29.5,488.0,0.9272,5.0,5.0

The most important information in batch files is the formula used to create that batch and the resulting quality (Vicosity).<br>
Except for the Outer, the 'mix' file only contains information about the Batch but not the Outer Formulation. <br>
<br>
'merge_1' will be paired with 'outer_b' to retrieve the associated recipe information.<br>
The results will then be linked to each formulation file.

## 4. MERGE 'MERGE_1' AND 'OUTER_B'

In [49]:
outer_b_c.columns

Index(['Formulation', 'Batch Number '], dtype='object')

In [50]:
outer_b_c['Batch Number '] = outer_b_c['Batch Number '].str.strip()
outer_b_c['Formulation'] = outer_b_c['Formulation'].str.strip()

In [51]:
print(outer_b_c['Batch Number '].unique())

['BNO00001' 'BNO00002' 'BNO00003' 'BNO00004' 'BNO00005' 'BNO00006'
 'BNO00007' 'BNO00008' 'BNO00009' 'BNO00010' 'BNO00011' 'BNO00012'
 'BNO00013' 'BNO00014' 'BNO00015' 'BNO00016' 'BNO00017' 'BNO00018'
 'BNO00019' 'BNO00020' 'BNO00021' 'BNO00022' 'BNO00023' 'BNO00024'
 'BNO00025' 'BNO00026' 'BNO00027' 'BNO00028' 'BNO00029' 'BNO00030'
 'BNO00031' 'BNO00032' 'BNO00033' 'BNO00034' 'BNO00035' 'BNO00036'
 'BNO00037' 'BNO00038' 'BNO00039' 'BNO00040' 'BNO00041' 'BNO00042'
 'BNO00043' 'BNO00044' 'BNO00045' 'BNO00046' 'BNO00047' 'BNO00048'
 'BNO00049' 'BNO00050' 'BNO00051' 'BNO00052' 'BNO00053' 'BNO00054'
 'BNO00055' 'BNO00056' 'BNO00057' 'BNO00058' 'BNO00059' 'BNO00060'
 'BNO00061' 'BNO00062' 'BNO00063' 'BNO00064' 'BNO00065' 'BNO00066'
 'BNO00067' 'BNO00068' 'BNO00069' 'BNO00070' 'BNO00071' 'BNO00072'
 'BNO00073' 'BNO00074' 'BNO00075' 'BNO00076' 'BNO00077' 'BNO00078'
 'BNO00079' 'BNO00080' 'BNO00081' 'BNO00082' 'BNO00083' 'BNO00084'
 'BNO00085' 'BNO00086' 'BNO00087' 'BNO00088' 'BNO00089' 'BNO00090'
 'BNO00091' 'BNO00092' 'BNO00093' 'BNO00094' 'BNO00095' 'BNO00096'
 'BNO00097' 'BNO00098' 'BNO00099' 'BNO00100' 'BNO00101' 'BNO00102'
 'BNO00103' 'BNO00104' 'BNO00105' 'BNO00106' 'BNO00107' 'BNO00108'
 'BNO00109' 'BNO00110' 'BNO00111' 'BNO00112' 'BNO00113' 'BNO00114'
 'BNO00115' 'BNO00116' 'BNO00117' 'BNO00118' 'BNO00119' 'BNO00120'
 'BNO00121' 'BNO00122' 'BNO00123' 'BNO00124' 'BNO00125' 'BNO00126'
 'BNO00127' 'BNO00128' 'BNO00129' 'BNO00130' 'BNO00131' 'BNO00132'
 'BNO00133' 'BNO00134' 'BNO00135' 'BNO00136' 'BNO00137' 'BNO00138'
 'BNO00139' 'BNO00140' 'BNO00141' 'BNO00142' 'BNO00143' 'BNO00144'
 'BNO00145' 'BNO00146' 'BNO00147' 'BNO00148' 'BNO00149' 'BNO00150'
 'BNO00151' 'BNO00152' 'BNO00153' 'BNO00154' 'BNO00155' 'BNO00156'
 'BNO00157' 'BNO00158' 'BNO00159' 'BNO00160' 'BNO00161' 'BNO00162'
 'BNO00163' 'BNO00164' 'BNO00165' 'BNO00166' 'BNO00167' 'BNO00168'
 'BNO00169' 'BNO00170' 'BNO00171' 'BNO00172' 'BNO00173' 'BNO00174'
 'BNO00175' 'BNO00176' 'BNO00177' 'BNO00178' 'BNO00179' 'BNO00180'
 'BNO00181' 'BNO00182' 'BNO00183' 'BNO00184' 'BNO00185' 'BNO00186'
 'BNO00187' 'BNO00188' 'BNO00189' 'BNO00190' 'BNO00191' 'BNO00192'
 'BNO00193' 'BNO00194' 'BNO00195' 'BNO00196' 'BNO00197' 'BNO00198'
 'BNO00199' 'BNO00200' 'BNO00201' 'BNO00202' 'BNO00203' 'BNO00204'
 'BNO00205' 'BNO00206' 'BNO00207' 'BNO00208' 'BNO00209' 'BNO00210'
 'BNO00211' 'BNO00212' 'BNO00213' 'BNO00214' 'BNO00215' 'BNO00216'
 'BNO00217' 'BNO00218' 'BNO00219' 'BNO00220' 'BNO00221' 'BNO00222'
 'BNO00223' 'BNO00224' 'BNO00225' 'BNO00226' 'BNO00227' 'BNO00228'
 'BNO00229' 'BNO00230' 'BNO00231' 'BNO00232' 'BNO00233' 'BNO00234'
 'BNO00235' 'BNO00236' 'BNO00237' 'BNO00238' 'BNO00239' 'BNO00240'
 'BNO00241' 'BNO00242' 'BNO00243' 'BNO00244' 'BNO00245' 'BNO00246'
 'BNO00247' 'BNO00248' 'BNO00249' 'BNO00250' 'BNO00251' 'BNO00252'
 'BNO00253' 'BNO00254']

In [52]:
print(outer_b_c['Formulation'].unique())

['Telos outer (rusty PVA)' 'AXF_1 outer' 'Telos outer'
 'AXF_1 outer (Salty)' 'Telos Outer' '2.25/38G/7' '2.25/34G/7' '4/15/7'
 '8/0/7' '6/10/7' '7/5/7' 'AXF-1 outer Thicc' '2.25/38P/7' '4.5/14.7P/4'
 'Osmo matched 96/4 outer' '1.5/0.1875%18-88/38P/7' '2.25/38M/7'
 '4.5/14.7M/4' '4.5/19M/6' '3.35/27G/7' '3.35/27M/7' '4.45/16P/7'
 '3.35/27P/7' '2.25/27P/11S/7' '2.25/38S/7' '4.5/14.3P/6' '4.5/14.3S/6'
 '4.5/14.3G/6' '4.5/14.3M/6' '5.93/0/6' '4.5/19P/6' '4.5/10P/5.1S/7'
 '2.25/27P11S/7' '4.5/19P/7' '4.5/19MPG/7' '2.25/11.7G/32.5S/1'
 '2.25/28.08P/8.99S/7.87']

In [53]:
outer_b_c.rename(columns = {'Batch Number ': 'Outer used'}, inplace = True)

In [54]:
merge_2 = merge_1.merge(outer_b_c,how='left', on=['Outer used'])
merge_2.info()
print('-'*50)
merge_2.head(5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149 entries, 0 to 148
Data columns (total 33 columns):
 #   Column                                               Non-Null Count  Dtype
---  ------                                               --------------  -----
 0   AXF Number                                           149 non-null    object
 1   Core used                                            149 non-null    object
 2   Core Formulation                                     149 non-null    object
 3   Core Viscosity (cP)                                  149 non-null    float64
 4   Amount of Core Used (g)                              149 non-null    float64
 5   UV used                                              149 non-null    object
 6   UV formulation                                       149 non-null    object
 7   UV viscosity (cP)                                    149 non-null    float64
 8   Amount of UV Used (g)                                149 non-null    float64
 9   Emulsion viscosity (cP)                              149 non-null    float64
 10  Emulsion Gear Pump used                              149 non-null    object
 11  Single Emulsion (SE) Number                          149 non-null    object
 12  Vessel Used                                          149 non-null    object
 13  Impellor Used                                        149 non-null    object
 14  Mass of emulsion used / g                            149 non-null    float64
 15  Impellor Speed (rpm)                                 149 non-null    float64
 16  Core Loading (%)                                     149 non-null    float64
 17  Outer used                                           149 non-null    object
 18  Outer viscosity (cP)                                 149 non-null    float64
 19  Outer Gear Pump Used                                 149 non-null    object
 20  Dispersed Flow Rate (mL/min)                         149 non-null    float64
 21  Continuous Flow Rate (mL/min)                        149 non-null    float64
 22  Flow Rate Ratio                                      149 non-null    float64
 23  Cure Rig Used                                        149 non-null    object
 24  Membrane Used (µm)                                   149 non-null    float64
 25  Insert used (mm)                                     149 non-null    float64
 26  Length of curing tubing (m)                          149 non-null    float64
 27  Temperature of Outer Phase at end of experiment / C  149 non-null    object
 28  UV Power (J s-1)                                     149 non-null    float64
 29  Curing Energy (kJ g-1)                               149 non-null    float64
 30  % dry after 24h in humidity                          149 non-null    float64
 31  % dry after 2 days in humidity chamber               149 non-null    float64
 32  Formulation                                          149 non-null    object
dtypes: float64(19), object(14)
memory usage: 38.5+ KB
--------------------------------------------------

,AXF Number,Core used,Core Formulation,Core Viscosity (cP),Amount of Core Used (g),UV used,UV formulation,UV viscosity (cP),Amount of UV Used (g),Emulsion viscosity (cP),...,Cure Rig Used,Membrane Used (µm),Insert used (mm),Length of curing tubing (m),Temperature of Outer Phase at end of experiment / C,UV Power (J s-1),Curing Energy (kJ g-1),% dry after 24h in humidity,% dry after 2 days in humidity chamber,Formulation
0,AXF0119,BNC00041,RAD-C-0001,7356.0,1500.0,BNU00059,AUF076,254.4,3500.0,520.8,...,Cure Rig 1.0,20.0,9.0,50.0,34.9,708.0,2.5488,15.0,15.0,2.25/38G/7
1,AXF0128,BNC00044,RAD-C-0001,9036.0,1500.0,BNU00068,AUF110,375.6,3500.0,697.2,...,Cure Rig 1.0,20.0,9.0,50.0,28.5,708.0,1.6992,50.0,60.0,2.25/38G/7
2,AXF0129,BNC00044,RAD-C-0001,9036.0,1500.0,BNU00068,AUF110,375.6,3500.0,697.2,...,Cure Rig 1.0,20.0,9.0,50.0,28.7,488.0,1.1712,30.0,70.0,2.25/38G/7
3,AXF0130,BNC00044,RAD-C-0001,9036.0,1500.0,BNU00068,AUF110,375.6,3500.0,697.2,...,Cure Rig 1.0,20.0,9.0,50.0,29.5,488.0,0.9272,2.0,5.0,2.25/38G/7
4,AXF0130,BNC00044,RAD-C-0001,9036.0,1500.0,BNU00068,AUF110,375.6,3500.0,697.2,...,Cure Rig 1.0,20.0,9.0,50.0,29.5,488.0,0.9272,5.0,5.0,2.25/38G/7

The 'Formulation' column needs to be renamed to 'Outer formulation' to distinguish it from other formulations.

In [55]:
merge_2.rename(columns = {'Formulation' : 'Outer formulation'}, inplace = True)

## 5. MERGE 'MERGE_2' AND FORMULATION FILES

In [56]:
merge_2.columns

Index(['AXF Number', 'Core used', 'Core Formulation', 'Core Viscosity (cP)',
       'Amount of Core Used (g)', 'UV used', 'UV formulation',
       'UV viscosity (cP)', 'Amount of UV Used (g)', 'Emulsion viscosity (cP)',
       'Emulsion Gear Pump used', 'Single Emulsion (SE) Number', 'Vessel Used',
       'Impellor Used', 'Mass of emulsion used / g', 'Impellor Speed (rpm)',
       'Core Loading (%)', 'Outer used', 'Outer viscosity (cP)',
       'Outer Gear Pump Used', 'Dispersed Flow Rate (mL/min)',
       'Continuous Flow Rate (mL/min)', 'Flow Rate Ratio', 'Cure Rig Used',
       'Membrane Used (µm)', 'Insert used (mm)', 'Length of curing tubing (m)',
       'Temperature of Outer Phase at end of experiment / C',
       'UV Power (J s-1)', 'Curing Energy (kJ g-1)',
       '% dry after 24h in humidity', '% dry after 2 days in humidity chamber',
       'Outer formulation'],
      dtype='object')

In [57]:
uv_c.columns

Index(['Sample', 'ESBOA', 'Epoxy:GPTA 75:25', 'Miramer PU2560',
       'Photocryl DP408NT (40% DPGDA)', 'Miramer U360NT', 'Miramer U3195NT',
       'Miramer U3926NT', 'Miramer U3969NT', 'Miramer MU9800',
       'Miramer PU2100NT', 'Miramer SIU2400', 'Miramer SIP900',
       'Miramer SP1106', 'BR-5541M', 'BR-640D', 'BR-643', 'BR-990', 'BRC-843D',
       'CN9276', 'PEG200Da', 'PEG360MA', 'Miramer M142 (PHEA-2)',
       'Lauryl Acrylate', 'IDA', 'TPGDA', 'TMP(3EO)TA', 'TMPTA', 'HDDA',
       'SR833S', 'SR399', 'SR834', 'GPTA', 'SR295', 'IBOA', 'IPEMA',
       'Miramer M180 (Stearyl Acrylate)', 'Miramer M166 (NP(EO8)A)',
       'Miramer M2101 (BPA(EO)10DMA', 'Miramer M206 (HD(EO)nDA)',
       'Miramer M4004 (PE(EO)nTA)', 'Sarbio 5201 (DDDA)',
       'Miramer M222 (DPGDA)', 'Miramer 144 (PHEA-4)', 'Debonding Reading',
       'UVF339 (CAB in HDDA)', 'UVF540 (Diamond Solucote in HDDA)',
       'LU62406 (Diamond Receptive in HDDA)', 'LU62407(Diamond CAP in HDDA)',
       'LU62408 (G1159 in HDDA))', 'LU62405 (A81 in HDDA)',
       'Omnirad 819 (BAPO) -Type I', 'BDK - Type I', 'Omnirad MBF - Type II',
       'Omnipol BP - Polymeric Type II', 'Omnirad 1173 - Type I',
       'BP2702/2959 (80:20 blend) -Type II/I', 'TPO-L -Type I',
       'DETX - Type II', 'MBB - Type II', 'MBZ - Type II',
       'Omnirad 184 -Type I', 'JRcure1919', 'JRcure1607', 'Chiguard',
       'Tinuvin123', 'Tinuvin1130', 'Tetrabromomethane', 'Titanium Dioxide',
       'Agitan 760', 'Radwax 15/30', 'Radactive SF', 'Tego Wet 270',
       'Tego Glide 432', 'Tego wet 288', 'Foamtroll 110', 'Aerosil R816',
       'Aerosil E805', 'Aerosil E812', 'HS417-1', 'Gasil HP33C', 'Span80',
       'Synperonic 91/2.5 LQ', 'Agitan DF 6422', 'TEA', 'GC1100Y',
       'Agisyn 008', 'GC1000Z', 'Total'],
      dtype='object')

In [58]:
core_c.columns

Index(['Sample', 'Klucel E', 'Klucel ELF ', 'Nisso 40 K ', 'Nisso 100 K ',
       'Hyd HPC unknown MW', 'Hyd HPC 7k', 'Hyd HPC 15k', 'Hyd HPC 20k',
       'Hyd KE HPC 9k', 'Hyd KE HPC 5k', 'NaCl', 'CaCl2', 'PDO', 'Glycerol ',
       '1,5-PDO', 'MPG ', 'C12E6', 'Water ', 'Go Water Solution (0.3%?)',
       'PEG550DMA ', 'PEG200', 'Total'],
      dtype='object')

In [59]:
outer_c.columns

Index(['Sample', 'NaCl', 'Glycerol', 'PDO', 'MPG', 'Sugar',
       'PVA (10% in water)', 'Water'],
      dtype='object')

Notice that the first 'core_c' and 'outer_c' have the name column 'Water'; these need to be changed to differentiate them.

In [60]:
core_c.rename(columns = {'Water ': 'Water_core'}, inplace = True)
outer_c.rename(columns = {'Water': 'Water_outer'}, inplace = True)

The 'Total' column in both 'uv_c' and 'core_c' is not necessary for analyzing the relationship with the object to be optimized. They will be dropped.

In [61]:
uv_c = uv_c.drop(columns='Total')
core_c = core_c.drop(columns='Total')

The 'Sample' column of the formulation files needs to be renamed correctly according to the formulation for merging with 'merge_2'.

In [62]:
uv_c.rename(columns = {'Sample': 'UV formulation'}, inplace = True)
core_c.rename(columns = {'Sample': 'Core Formulation'}, inplace = True)
outer_c.rename(columns = {'Sample': 'Outer formulation'}, inplace = True)

Merging files

In [63]:
merge_3 = merge_2.merge(uv_c,how = 'left', on=['UV formulation'])
merge_4 = merge_3.merge(core_c,how = 'left', on=['Core Formulation'])
final = merge_4.merge(outer_c,how ='left', on=['Outer formulation'])
final.info()
print('-'*50)
final

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149 entries, 0 to 148
Columns: 148 entries, AXF Number to Water_outer
dtypes: float64(134), object(14)
memory usage: 172.4+ KB
--------------------------------------------------

,AXF Number,Core used,Core Formulation,Core Viscosity (cP),Amount of Core Used (g),UV used,UV formulation,UV viscosity (cP),Amount of UV Used (g),Emulsion viscosity (cP),...,Go Water Solution (0.3%?),PEG550DMA,PEG200,NaCl_y,Glycerol,PDO_y,MPG,Sugar,PVA (10% in water),Water_outer
0,AXF0119,BNC00041,RAD-C-0001,7356.0,1500.0,BNU00059,AUF076,254.4,3500.0,520.8,...,0.0,0.0,0.0,7.0,38.0,0.0,0.0,0.0,2.25,52.75
1,AXF0128,BNC00044,RAD-C-0001,9036.0,1500.0,BNU00068,AUF110,375.6,3500.0,697.2,...,0.0,0.0,0.0,7.0,38.0,0.0,0.0,0.0,2.25,52.75
2,AXF0129,BNC00044,RAD-C-0001,9036.0,1500.0,BNU00068,AUF110,375.6,3500.0,697.2,...,0.0,0.0,0.0,7.0,38.0,0.0,0.0,0.0,2.25,52.75
3,AXF0130,BNC00044,RAD-C-0001,9036.0,1500.0,BNU00068,AUF110,375.6,3500.0,697.2,...,0.0,0.0,0.0,7.0,38.0,0.0,0.0,0.0,2.25,52.75
4,AXF0130,BNC00044,RAD-C-0001,9036.0,1500.0,BNU00068,AUF110,375.6,3500.0,697.2,...,0.0,0.0,0.0,7.0,38.0,0.0,0.0,0.0,2.25,52.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,AXF0499,BNC00100,RAD-C-0002,10360.0,929.1,BNU00123,AUF110,318.0,2099.9,724.8,...,0.0,0.0,0.0,7.0,0.0,0.0,38.0,0.0,2.25,52.75
145,AXF0500,BNC00100,RAD-C-0002,10360.0,929.1,BNU00123,AUF110,318.0,2099.9,724.8,...,0.0,0.0,0.0,7.0,0.0,0.0,38.0,0.0,2.25,52.75
146,AXF0500,BNC00100,RAD-C-0002,10360.0,929.1,BNU00123,AUF110,318.0,2099.9,724.8,...,0.0,0.0,0.0,7.0,0.0,0.0,38.0,0.0,2.25,52.75
147,AXF0501,BNC00100,RAD-C-0002,10360.0,929.1,BNU00123,AUF110,318.0,2099.9,724.8,...,0.0,0.0,0.0,7.0,0.0,0.0,38.0,0.0,2.25,52.75
148,AXF0501,BNC00100,RAD-C-0002,10360.0,929.1,BNU00123,AUF110,318.0,2099.9,724.8,...,0.0,0.0,0.0,7.0,0.0,0.0,38.0,0.0,2.25,52.75

In [64]:
for col in final.columns:
    try:
        final[col] = final[col].astype('float64')
    except:
        pass

In [ ]:
#final.to_csv('../data/processed/final.csv', index = False)